### ISSUE TITLE
Can't install detectron2

### ISSUE THREAD

**Issue by billop** [python-poetry/poetry#2113]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.0.5
- **Contents of your pyproject.toml file**:
```toml
[tool.poetry]
name = "a"
version = "0.1.0"
description = ""
authors = ["a"]

[tool.poetry.dependencies]
python = "^3.6"
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Issue

Poetry can't figure out the version of [detectron2](https://github.com/facebookresearch/detectron2/blob/33e022db2c988ae15c65d9e409711d1693b917d5/setup.py#L122). I've tried to debug this myself but the error messages don't tell me anything useful:

```
$ /tmp/poetry/bin/poetry install -vvv

Creating virtualenv a-1_qs6r2x-py3.8 in /home/x/.cache/pypoetry/virtualenvs
Using virtualenv: /home/x/.cache/pypoetry/virtualenvs/a-1_qs6r2x-py3.8
Updating dependencies
Resolving dependencies...
   1: fact: a is 0.1.0
   1: derived: a
   1: fact: a depends on detectron2 (*)
   1: selecting a (0.1.0)
   1: derived: detectron2 (*)
   1: Version solving took 3.842 seconds.
   1: Tried 1 solutions.

[RuntimeError]
Unable to retrieve the package version for /tmp/pypoetry-git-detectron2683igqav

Traceback (most recent call last):
  File "/tmp/poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/tmp/poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/tmp/poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/tmp/poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/tmp/poetry/lib/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/tmp/poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/tmp/poetry/lib/poetry/installation/installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "/tmp/poetry/lib/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/tmp/poetry/lib/poetry/puzzle/solver.py", line 180, in _solve
    result = resolve_version(
  File "/tmp/poetry/lib/poetry/mixology/__init__.py", line 7, in resolve_version
    return solver.solve()
  File "/tmp/poetry/lib/poetry/mixology/version_solver.py", line 80, in solve
    next = self._choose_package_version()
  File "/tmp/poetry/lib/poetry/mixology/version_solver.py", line 355, in _choose_package_version
    packages = self._provider.search_for(dependency)
  File "/tmp/poetry/lib/poetry/puzzle/provider.py", line 130, in search_for
    packages = self.search_for_vcs(dependency)
  File "/tmp/poetry/lib/poetry/puzzle/provider.py", line 167, in search_for_vcs
    package = self.get_package_from_vcs(
  File "/tmp/poetry/lib/poetry/puzzle/provider.py", line 204, in get_package_from_vcs
    package = cls.get_package_from_directory(tmp_dir, name=name)
  File "/tmp/poetry/lib/poetry/puzzle/provider.py", line 343, in get_package_from_directory
    raise RuntimeError(

```

Is poetry unable to get dynamically generated versions?

**Comment by malcolmgreaves** [comment]
Came to file a bug about not being able to install `detectron2` -- as of `poetry` `1.1.3` it's still not installable.

detectron2 needs `torch` to install:
```
$ poetry install
Updating dependencies
Resolving dependencies... (4.5s)

  PackageInfoError

  Unable to determine package info for path: /tmp/pypoetry-git-detectron2dazfvgem

  Fallback egg_info generation failed.

  Command ['/tmp/tmpp_0xdcph/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output:
  Traceback (most recent call last):
    File "setup.py", line 10, in <module>
      import torch
  ModuleNotFoundError: No module named 'torch'

  at ~/.poetry/lib/poetry/inspection/info.py:503 in _pep517_metadata
      499│                     venv.run("python", "setup.py", "egg_info")
      500│                     return cls.from_metadata(path)
      501│                 except EnvCommandError as fbe:
      502│                     raise PackageInfoError(
    → 503│                         path, "Fallback egg_info generation failed.", fbe
      504│                     )
      505│                 finally:
      506│                     os.chdir(cwd.as_posix())
      507│
```

Even though I explicitly have `torch` as a dependency:
```
[tool.poetry]
name = "my_project"
version = "0.0.0"
description = ""
authors = ["Me <me@me.com>"]
license = "None"

[tool.poetry.dependencies]
python = "^3.7"
torch = "1.4"
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git", branch = "master" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.1.3"]
build-backend = "poetry.core.masonry.api"
```

Curiously, if I remove the `detectron2` line, do `poetry install`, then add back the `detectron2` line and do `poetry shell`, I am able to follow the project's [installation instructions](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md) successfully:
```
poetry
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
```
But, even if I do the above w/o manually doing `python -m pip`, i.e. a `poetry update` instead, (so there's still torch) it doesn't work (same error).

**Comment by malcolmgreaves** [comment]
I imagine this might be a difficult problem (building wheels from general `setup.py`s). Any chance that there's a way to have poetry try to install other dependencies first before doing `git` installable ones? (Does this even make sense? @finswimmer if you have any time to look into this 🙏 )

**Comment by abn** [comment]
@malcolmgreaves the issue is that the library does not add `torch` to it's `build-backend.requires`. This is not something poetry can resolve, even if we install torch into the project's virtualenv. The build for detectron happens in it's own isolated environment with whatever it declares as it's build requirements.

**Comment by malcolmgreaves** [comment]
😭  Oh that's very unfortunate!

I appreciate the very prompt reply @abn 💯

**Comment by abn** [comment]
No worries. Wish it was a more helpful response. You can just send them a PR with a minimal `pyproject.toml`. In the interim, you can use a branch on your fork with the change.

**Comment by malcolmgreaves** [comment]
@abn Would the minimum viable `pyproject.toml` be to specify that `torch`, alongside `setuptools` and `wheel`, is a requirement of the build system? i.e. does this formulation make sense?
https://github.com/malcolmgreaves/detectron2/pull/2/files

(I originally first thought that I should make it a poetry project https://github.com/malcolmgreaves/detectron2/pull/1/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711 But then realized that it should be possible to keep their build current build system, but just indicate that building the wheel requires `torch` too, right?)

**Comment by malcolmgreaves** [comment]
🎉  I have answered my own question -- just adding `torch` to `requires` in the `build-system` section is all that's necessary to get `poetry` to understand how to build the `detectron2` wheel! 🎉 

```
[build-system]
requires = ["setuptools", "wheel", "torch"]
```

**Comment by abn** [comment]
@malcolmgreaves for completeness this is what you need to keep legacy build.

```toml
[build-system]
requires = ["setuptools", "wheel", "torch"]
build-backend = "setuptools.build_meta:__legacy__"
```

**Comment by malcolmgreaves** [comment]
Great! Thank you a ton 💯 💯 🤗

**Comment by abn** [comment]
I am going to cose this issue as the original issue has been resolved and the current issue has to do with lack of PEP 517 metadata in the package source.

**Comment by joostmeulenbeld** [comment]
@malcolmgreaves I have this exact same issue, did you open a pull request at the original Detectron2 repo?

**Comment by malcolmgreaves** [comment]
@joostmeulenbeld I have a workaround here -- you can `poetry install` this as a `{ git = ... }` dependency
https://github.com/malcolmgreaves/detectron2

**Comment by iamlucaswolf** [comment]
@malcolmgreaves I just tried your workaround to integrate detectron2 with an existing project but still get errors... 😕 

My pyproject.toml looks like this:

```toml
[tool.poetry.dependencies]
...
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git"}

[build-system]
requires = ["setuptols", "wheel", "torch"]
build-backend = "setuptools.build_meta:__legacy__"
```

However, when I run `poetry install`, I get:

```python3
PackageInfoError

  Unable to determine package info for path: /tmp/pypoetry-git-detectron20h25u89n
  
  Fallback egg_info generation failed.
  
  Command ['/tmp/tmpi8lubyub/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "/tmp/pypoetry-git-detectron20h25u89n/setup.py", line 10, in <module>
      import torch
  ModuleNotFoundError: No module named 'torch'

  at ~/.poetry/lib/poetry/inspection/info.py:502 in _pep517_metadata
      498│                 try:
      499│                     venv.run("python", "setup.py", "egg_info")
      500│                     return cls.from_metadata(path)
      501│                 except EnvCommandError as fbe:
    → 502│                     raise PackageInfoError(
      503│                         path, "Fallback egg_info generation failed.", fbe
      504│                     )
      505│                 finally:
      506│                     os.chdir(cwd.as_posix())
```

Any idea why that might be the case?

**Comment by lucinvitae** [comment]
I'm also still seeing this same issue with installing detectron2 using poetry 1.1.6 despite adding the poetry configuration mentioned in https://github.com/python-poetry/poetry/issues/2113#issuecomment-711075790

Relevant poetry configuration:
```toml
[tool.poetry.dependencies]
python = "^3.8"
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git", branch = "master" }

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel", "torch"]
build-backend = "setuptools.build_meta:__legacy__"
```

Exception stacktrace for poetry lock:
```
$ poetry lock
Updating dependencies
Resolving dependencies... (11.9s)

  PackageInfoError

  Unable to determine package info for path: /var/folders/1p/flnst32s2vv8gl821zrsn_hh0000gp/T/pypoetry-git-detectron2_rgh_58o

  Fallback egg_info generation failed.

  Command ['/var/folders/1p/flnst32s2vv8gl821zrsn_hh0000gp/T/tmpa6vvz2kw/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output:
  Traceback (most recent call last):
    File "setup.py", line 10, in <module>
      import torch
  ModuleNotFoundError: No module named 'torch'

  at ~/.pyenv/versions/3.8.9/envs/layoutlmv2_lib/lib/python3.8/site-packages/poetry/inspection/info.py:502 in _pep517_metadata
      498│                 try:
      499│                     venv.run("python", "setup.py", "egg_info")
      500│                     return cls.from_metadata(path)
      501│                 except EnvCommandError as fbe:
    → 502│                     raise PackageInfoError(
      503│                         path, "Fallback egg_info generation failed.", fbe
      504│                     )
      505│                 finally:
      506│                     os.chdir(cwd.as_posix())
```
`poetry install` fails similarly.

@abn I see that you closed this due to "lack of PEP 517 metadata in the package source.". However, is there the possibility of changing the way the detectron2 package is installed by adding the torch dependency beforehand somehow? e.g.
```
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git", branch = "master", install_requires = "torch" }
```

I realize this may come across as a new feature request, but I'm not sure how else to proceed without forking the detectron2 project. If you see [here](https://github.com/facebookresearch/detectron2/issues/2644#issuecomment-782929567), the maintainers of the detectron2 project do not appear open to fixing this issue on their side:

> Because poetry does not support selecting cuda version python-poetry/poetry#2145 there is no reasonable way to support detectron2.

For now, this is our workaround, in a project `Dockerfile` 😢 
```
RUN poetry install -vvv --no-root \
    && pip uninstall poetry -y \
    && rm -rf ~/.config/pypoetry

# Workaround for issue where detectron2 cannot be installed with poetry:
# - https://github.com/python-poetry/poetry/issues/2113
# - https://github.com/facebookresearch/detectron2/issues/2644
RUN python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
```

**Comment by ppwwyyxx** [comment]
>  the maintainers of the detectron2 project do not appear open to fixing this issue on their side

We are open as long as there is a reasonable fix. From what I can see that's not the case due to limitations in poetry (and all other python package management tools).

**Comment by lucinvitae** [comment]
Thanks for chiming in, @ppwwyyxx, good to know that you are open to helping solve this issue. Maybe @abn or another maintainer (@sdispater?) from the poetry side has an idea how to remove such limitations. 

The comments that @abn made above [[1](https://github.com/python-poetry/poetry/issues/2113#issuecomment-710834646), [2](https://github.com/python-poetry/poetry/issues/2113#issuecomment-711089585)] led me to believe this was something that needed to be addressed on the detectron2 project-side, and not the poetry side. 

Perhaps the poetry maintainers require more information as to how they could remove the limitations you are mentioning. It's not clear to me, but for now, the result is that we cannot use poetry to install detectron2.

**Comment by mzhadigerov** [comment]
I'm getting the same bug as @lucinvitae . All I want to do is something similar to `pip install "git+https://github.com/facebookresearch/detectron2.git@v0.5#egg=detectron2"`

**Comment by abn** [comment]
@lucinvitae as far as I can tell, the issue here is the package build specification does to convey that it needs `torch` to successfully build the package. Let me know if this is not the case.

Fro poetry's perspective, we first need to build the bdist of the package if a compatible one is not already available on the configured indices. This will lead to a poetry attempting to build the package's wheel, this happens inside an ephemeral isolated build environment according to PEP-517. When creating this environment, the `build-system` requirements are installed. In this case, since the build scripts need `torch` available (https://github.com/python-poetry/poetry/issues/2113#issuecomment-711075790). Essentially, something similar to the following is what happens under the hood. 

```console
root@c9958409c9fd:/# python -m pip wheel --disable-pip-version-check --use-pep517 git+https://github.com/facebookresearch/detectron2.git
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-ax2ddphy
  Running command git clone -q https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-ax2ddphy
  Resolved https://github.com/facebookresearch/detectron2.git to commit c081505af16f54c5a013916b81636d03f7c0a8fd
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmphk82qqi5
       cwd: /tmp/pip-req-build-ax2ddphy
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-slhwwdsz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-slhwwdsz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-slhwwdsz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-slhwwdsz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 10, in <module>
      import torch
  ModuleNotFoundError: No module named 'torch'
  ----------------------------------------
WARNING: Discarding git+https://github.com/facebookresearch/detectron2.git. Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmphk82qqi5 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmphk82qqi5 Check the logs for full command output.
```

However, as @ppwwyyxx identified, there are other limitations that limit the options you have at the moment - ie. you cannot discover automatically the pre-built wheels provided by `detectron2` nor can they distribute CUDA wheels on PyPI.

For instance, poetry resolver today does not handle local tags well neither does using link repositories work. This means that you cannot use the indices described in https://github.com/facebookresearch/detectron2/blob/main/INSTALL.md#install-pre-built-detectron2. However, you can use the direct links to the wheels here, but this assumes everwhere you install your package the same wheel can be used (this should be fine for cpu, alternatively you can have various extras. This is being fixed (partially done).

That said, I do not think the python packaging ecosystem has a decent solution for gpu packages anyway - eg. there is no standard way to determine if a cuda enabled wheel can be used in active environment.

- https://discuss.python.org/t/what-to-do-about-gpus-and-the-built-distributions-that-support-them/7125
- https://mail.python.org/archives/list/distutils-sig@python.org/thread/LXLF4YSC4WUZOYRX65DW7CESIX7UUBK5/

Having the dependency metadata specify something like `{ ..., extra-build-requires = ["torch"] }` might be an option, but I am not sure if we should start doing this. On the one hand, this enables poetry users to consume packages where similar issues exist more cleanly (this won't solve the gpu issue), on the other hand this is a workaround for lack of standard metadata.

Another option is to allow for something like `{ ..., build-allow-system-site = true }`. In this case, the system packages are allowed for package builds.

What poetry should do in the near future are the following:
1. Allow for `--find-link` type sources in projects.
2. Support local version tags for dependency resolution and package installation.

I still think that the `torch` dependency need to be declared in the project's metadata (not in downstream packages) if it is required at build time, so that PEP-517 builds can work correctly.

As for the gpu specific versions, I am not sure where this needs to go. Ideally, there will be a packaging PEP that will help tools like 'poetry' to implement a standardised approach.

**Comment by abn** [comment]
Also, I'd recommend this moves to a discussion instead of this closed issue.

**Comment by mzhadigerov** [comment]
What's the solution, then? How to add detectron2 using poetry? @abn

**Comment by satishjasthi** [comment]
> @malcolmgreaves for completeness this is what you need to keep legacy build.
> 
> ```toml
> [build-system]
> requires = ["setuptools", "wheel", "torch"]
> build-backend = "setuptools.build_meta:__legacy__"
> ```

Thanks a lot this solution works
once you update it, just use 
`poetry add path_to_detectron2_wheel_file`

**Comment by Maciej-Zwolinski** [comment]
This seems to no longer work - or at least not in the general case.

The issue that everyone seems to be missing - please correct me if I'm wrong about it - is that simply specifying `torch` or even `torch==1.10.2` in build-system section of `detectron2` does not solve the true problem - that is that **torch version you install - whatever that version might be - has to be compiled for the same CUDA version you have on your machine**.

Since `torch` available @pypi is compiled by default with CUDA 10.2 (or at least newer versions are), this **FORCES** CUDA 10.2 onto your system - something the authors of `detectron2` have no chance of fixing. @ppwwyyxx 

The problem runs even deeper. Even if `detectron2` is forked, and proper version of torch is required in the minimal `pyproject.toml`, there is seems to be no way (@1) of forcing build process to download and use custom wheel - such as available at https://download.pytorch.org/whl/cu113 - which would be required to build `detectron2` using specific CUDA version...

^1. please confirm this, I'm new to setuptools and custom package building in general.

**Comment by helpmefindaname** [comment]
I managed to get it run by specifying:

```
[build-system]
requires = ["setuptools", "wheel", "torch==1.10.2+cu113", "torchvision==0.11.3+cu113", "ninja2"]
build-backend = "setuptools.build_meta:__legacy__"
```

in a detectron2 fork

using the following config

```
[tool.poetry]
name = "test_detectron_poetry"
version = "0.1.0"
description = ""
authors = ["Benedikt Fuchs <benedikt.fuchs.staw@hotmail.com>"]

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/"
secondary = true
default = false

[tool.poetry.dependencies]
python = "3.8.*"
torch = {version = "1.10.2+cu113", source = "torch"}
torchvision = "0.11.3+cu113"
detectron2 = {git = "https://github.com/helpmefindaname/detectron2.git", rev = "main"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```
using **poetry==1.2.0b2** following [this issue](https://github.com/python-poetry/poetry/issues/4231#issuecomment-1212856163), it is important to mention that this file **will not work** on the **latest non-beta release**

and additionally adding `https://download.pytorch.org/whl` as an extra index in the [global git config file](https://pip.pypa.io/en/stable/topics/configuration/#location)

The last step is necessary, as [PEP-518](https://peps.python.org/pep-0518/) specifies to use isolated builds for building wheels, so the index specified in poetry won't be used. However, globally configured indexes will also be used by the newly isolated venv.


Some side notes:
* on ubuntu, you need to have `gcc` and `g++` version below `10.*`, so you might have to manually downgrade the versions.
* I tried to get it to run on windows first, however there `venv` didn't manage to copy the isolated venv to a temp folder, failing the build before any detectron2 related code was executed. I suppose this is not related to this issue. I don't understand why that happens or if that is specific to my setup or not.
* You can expect to take a very long time for the first time. Even with setting `python="3.8.*"` it will download wheels for a veriety of python versions. You might want to ensure that `pip cache lost` is working before starting installing it. I had it disabled for some reason, which made it frustrating when my internet crashed, and I had to start downloading some wheels again.

**Comment by swicaksono** [comment]
Hi, does anyone have any solution to this issue? I still can't find a way to install detectron2. I tried https://github.com/python-poetry/poetry/issues/2113#issuecomment-1221601986 but got an error:
```bash
Resolving dependencies... (7.9s)

  CalledProcessError

  Command '['/tmp/tmpbzglt_2o/.venv/bin/python', '-']' returned non-zero exit status 1.

  at ~/.pyenv/versions/3.8.11/lib/python3.8/subprocess.py:516 in run
       512│             # We don't call process.wait() as .__exit__ does that for us.
       513│             raise
       514│         retcode = process.poll()
       515│         if check and retcode:
    →  516│             raise CalledProcessError(retcode, process.args,
       517│                                      output=stdout, stderr=stderr)
       518│     return CompletedProcess(process.args, retcode, stdout, stderr)
       519│ 
       520│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/tmp/tmpbzglt_2o/.venv/bin/python', '-'] errored with the following return code 1, and output: 
  ERROR: Could not find a version that satisfies the requirement torchvision==0.11.3+cu113 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.13.0, 0.13.1)
  ERROR: No matching distribution found for torchvision==0.11.3+cu113
  WARNING: You are using pip version 21.1.1; however, version 22.2.2 is available.
  You should consider upgrading via the '/tmp/build-env-wccfwciw/bin/python -m pip install --upgrade pip' command.
  Traceback (most recent call last):
    File "<stdin>", line 15, in <module>
    File "/tmp/tmpbzglt_2o/.venv/lib/python3.8/site-packages/build/env.py", line 211, in install
      _subprocess(cmd)
    File "/tmp/tmpbzglt_2o/.venv/lib/python3.8/site-packages/build/env.py", line 81, in _subprocess
      raise e
    File "/tmp/tmpbzglt_2o/.venv/lib/python3.8/site-packages/build/env.py", line 78, in _subprocess
      subprocess.check_output(cmd, stderr=subprocess.STDOUT)
    File "/home/sonywicaksono/.pyenv/versions/3.8.11/lib/python3.8/subprocess.py", line 415, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/home/sonywicaksono/.pyenv/versions/3.8.11/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/tmp/build-env-wccfwciw/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-u1urbb0b.txt']' returned non-zero exit status 1.
  input was : import build
  import build.env
  import pep517
  
  source = '/tmp/pypoetry-git-detectron2qmhb669o'
  dest = '/tmp/tmpbzglt_2o/dist'
  
  with build.env.IsolatedEnvBuilder() as env:
      builder = build.ProjectBuilder(
          srcdir=source,
          scripts_dir=env.scripts_dir,
          python_executable=env.executable,
          runner=pep517.quiet_subprocess_runner,
      )
      env.install(builder.build_system_requires)
      env.install(builder.get_requires_for_build('wheel'))
      builder.metadata_path(dest)
  

  at ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/utils/env.py:1421 in _run
      1417│                 output = subprocess.check_output(
      1418│                     cmd, stderr=subprocess.STDOUT, env=env, **kwargs
      1419│                 )
      1420│         except CalledProcessError as e:
    → 1421│             raise EnvCommandError(e, input=input_)
      1422│ 
      1423│         return decode(output)
      1424│ 
      1425│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int | None:

The following error occurred when trying to handle this error:


  CalledProcessError

  Command '['/tmp/tmpbzglt_2o/.venv/bin/python', 'setup.py', 'egg_info']' returned non-zero exit status 1.

  at ~/.pyenv/versions/3.8.11/lib/python3.8/subprocess.py:516 in run
       512│             # We don't call process.wait() as .__exit__ does that for us.
       513│             raise
       514│         retcode = process.poll()
       515│         if check and retcode:
    →  516│             raise CalledProcessError(retcode, process.args,
       517│                                      output=stdout, stderr=stderr)
       518│     return CompletedProcess(process.args, retcode, stdout, stderr)
       519│ 
       520│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/tmp/tmpbzglt_2o/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "setup.py", line 10, in <module>
      import torch
  ModuleNotFoundError: No module named 'torch'
  

  at ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/utils/env.py:1421 in _run
      1417│                 output = subprocess.check_output(
      1418│                     cmd, stderr=subprocess.STDOUT, env=env, **kwargs
      1419│                 )
      1420│         except CalledProcessError as e:
    → 1421│             raise EnvCommandError(e, input=input_)
      1422│ 
      1423│         return decode(output)
      1424│ 
      1425│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int | None:

The following error occurred when trying to handle this error:


  PackageInfoError

  Unable to determine package info for path: /tmp/pypoetry-git-detectron2qmhb669o
  
  Fallback egg_info generation failed.
  
  Command ['/tmp/tmpbzglt_2o/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "setup.py", line 10, in <module>
      import torch
  ModuleNotFoundError: No module named 'torch'
```

**Comment by neersighted** [comment]
> Hi, does anyone have any solution to this issue? I still can't find a way to install detectron2. I tried [#2113 (comment)](https://github.com/python-poetry/poetry/issues/2113#issuecomment-1221601986) but got an error:
> 
> ```shell
> Resolving dependencies... (7.9s)
> 
>   CalledProcessError
> 
>   Command '['/tmp/tmpbzglt_2o/.venv/bin/python', '-']' returned non-zero exit status 1.
> 
>   at ~/.pyenv/versions/3.8.11/lib/python3.8/subprocess.py:516 in run
>        512│             # We don't call process.wait() as .__exit__ does that for us.
>        513│             raise
>        514│         retcode = process.poll()
>        515│         if check and retcode:
>     →  516│             raise CalledProcessError(retcode, process.args,
>        517│                                      output=stdout, stderr=stderr)
>        518│     return CompletedProcess(process.args, retcode, stdout, stderr)
>        519│ 
>        520│ 
> 
> The following error occurred when trying to handle this error:
> 
> 
>   EnvCommandError
> 
>   Command ['/tmp/tmpbzglt_2o/.venv/bin/python', '-'] errored with the following return code 1, and output: 
>   ERROR: Could not find a version that satisfies the requirement torchvision==0.11.3+cu113 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.13.0, 0.13.1)
>   ERROR: No matching distribution found for torchvision==0.11.3+cu113
>   WARNING: You are using pip version 21.1.1; however, version 22.2.2 is available.
>   You should consider upgrading via the '/tmp/build-env-wccfwciw/bin/python -m pip install --upgrade pip' command.
>   Traceback (most recent call last):
>     File "<stdin>", line 15, in <module>
>     File "/tmp/tmpbzglt_2o/.venv/lib/python3.8/site-packages/build/env.py", line 211, in install
>       _subprocess(cmd)
>     File "/tmp/tmpbzglt_2o/.venv/lib/python3.8/site-packages/build/env.py", line 81, in _subprocess
>       raise e
>     File "/tmp/tmpbzglt_2o/.venv/lib/python3.8/site-packages/build/env.py", line 78, in _subprocess
>       subprocess.check_output(cmd, stderr=subprocess.STDOUT)
>     File "/home/sonywicaksono/.pyenv/versions/3.8.11/lib/python3.8/subprocess.py", line 415, in check_output
>       return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>     File "/home/sonywicaksono/.pyenv/versions/3.8.11/lib/python3.8/subprocess.py", line 516, in run
>       raise CalledProcessError(retcode, process.args,
>   subprocess.CalledProcessError: Command '['/tmp/build-env-wccfwciw/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-u1urbb0b.txt']' returned non-zero exit status 1.
>   input was : import build
>   import build.env
>   import pep517
>   
>   source = '/tmp/pypoetry-git-detectron2qmhb669o'
>   dest = '/tmp/tmpbzglt_2o/dist'
>   
>   with build.env.IsolatedEnvBuilder() as env:
>       builder = build.ProjectBuilder(
>           srcdir=source,
>           scripts_dir=env.scripts_dir,
>           python_executable=env.executable,
>           runner=pep517.quiet_subprocess_runner,
>       )
>       env.install(builder.build_system_requires)
>       env.install(builder.get_requires_for_build('wheel'))
>       builder.metadata_path(dest)
>   
> 
>   at ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/utils/env.py:1421 in _run
>       1417│                 output = subprocess.check_output(
>       1418│                     cmd, stderr=subprocess.STDOUT, env=env, **kwargs
>       1419│                 )
>       1420│         except CalledProcessError as e:
>     → 1421│             raise EnvCommandError(e, input=input_)
>       1422│ 
>       1423│         return decode(output)
>       1424│ 
>       1425│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int | None:
> 
> The following error occurred when trying to handle this error:
> 
> 
>   CalledProcessError
> 
>   Command '['/tmp/tmpbzglt_2o/.venv/bin/python', 'setup.py', 'egg_info']' returned non-zero exit status 1.
> 
>   at ~/.pyenv/versions/3.8.11/lib/python3.8/subprocess.py:516 in run
>        512│             # We don't call process.wait() as .__exit__ does that for us.
>        513│             raise
>        514│         retcode = process.poll()
>        515│         if check and retcode:
>     →  516│             raise CalledProcessError(retcode, process.args,
>        517│                                      output=stdout, stderr=stderr)
>        518│     return CompletedProcess(process.args, retcode, stdout, stderr)
>        519│ 
>        520│ 
> 
> The following error occurred when trying to handle this error:
> 
> 
>   EnvCommandError
> 
>   Command ['/tmp/tmpbzglt_2o/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output: 
>   Traceback (most recent call last):
>     File "setup.py", line 10, in <module>
>       import torch
>   ModuleNotFoundError: No module named 'torch'
>   
> 
>   at ~/.pyenv/versions/3.8.11/lib/python3.8/site-packages/poetry/utils/env.py:1421 in _run
>       1417│                 output = subprocess.check_output(
>       1418│                     cmd, stderr=subprocess.STDOUT, env=env, **kwargs
>       1419│                 )
>       1420│         except CalledProcessError as e:
>     → 1421│             raise EnvCommandError(e, input=input_)
>       1422│ 
>       1423│         return decode(output)
>       1424│ 
>       1425│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int | None:
> 
> The following error occurred when trying to handle this error:
> 
> 
>   PackageInfoError
> 
>   Unable to determine package info for path: /tmp/pypoetry-git-detectron2qmhb669o
>   
>   Fallback egg_info generation failed.
>   
>   Command ['/tmp/tmpbzglt_2o/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output: 
>   Traceback (most recent call last):
>     File "setup.py", line 10, in <module>
>       import torch
>   ModuleNotFoundError: No module named 'torch'
> ```

Please refer to the thread -- `detectron` has undeclared build-time dependencies and needs to be patched to either declare them or not require them. The correct incantations in `pyproject.toml` **in detectron** (most users having issues incorrectly added them to their project) are posted above. An upstream issue on this topic is locked, here: https://github.com/facebookresearch/detectron2/issues/2644

See this user's commit for an example of the patch:

https://github.com/devcsrj/detectron2/commit/c37c1fdfd48dc3cb317656cb863eccc61c5faa71

If you have more questions, please start a Discussion or join Discord -- this issue is not a great forum for support as problems in Poetry are already solved, and we are notifying many users unnecessarily.

**Comment by codingbutstillalive** [comment]
Has this issue been solved?

**Comment by ppwwyyxx** [comment]
All the claimed "solutions" or patches so far are incorrect, as explained in https://github.com/python-poetry/poetry/issues/2113#issuecomment-1145937065. This is why detectron2 did not accept any of these solutions.

**Comment by codingbutstillalive** [comment]
> All the claimed "solutions" or patches so far are incorrect, as explained in https://github.com/python-poetry/poetry/issues/2113#issuecomment-1145937065. This is why detectron2 did not accept any of these solutions.

So. It cannot be solved? Why does it work with pip then?

And why do you need CUDA if you just want to use it with CPU?

**Comment by codingbutstillalive** [comment]
> @lucinvitae as far as I can tell, the issue here is the package build specification does to convey that it needs `torch` to successfully build the package. Let me know if this is not the case.
> 
> 
> 
> Fro poetry's perspective, we first need to build the bdist of the package if a compatible one is not already available on the configured indices. This will lead to a poetry attempting to build the package's wheel, this happens inside an ephemeral isolated build environment according to PEP-517. When creating this environment, the `build-system` requirements are installed. In this case, since the build scripts need `torch` available (https://github.com/python-poetry/poetry/issues/2113#issuecomment-711075790). Essentially, something similar to the following is what happens under the hood. 
> 
> 
> 
> ```console
> 
> root@c9958409c9fd:/# python -m pip wheel --disable-pip-version-check --use-pep517 git+https://github.com/facebookresearch/detectron2.git
> 
> Collecting git+https://github.com/facebookresearch/detectron2.git
> 
>   Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-ax2ddphy
> 
>   Running command git clone -q https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-ax2ddphy
> 
>   Resolved https://github.com/facebookresearch/detectron2.git to commit c081505af16f54c5a013916b81636d03f7c0a8fd
> 
>   Installing build dependencies ... done
> 
>   Getting requirements to build wheel ... error
> 
>   ERROR: Command errored out with exit status 1:
> 
>    command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmphk82qqi5
> 
>        cwd: /tmp/pip-req-build-ax2ddphy
> 
>   Complete output (18 lines):
> 
>   Traceback (most recent call last):
> 
>     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
> 
>       main()
> 
>     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
> 
>       json_out['return_val'] = hook(**hook_input['kwargs'])
> 
>     File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
> 
>       return hook(config_settings)
> 
>     File "/tmp/pip-build-env-slhwwdsz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
> 
>       return self._get_build_requires(
> 
>     File "/tmp/pip-build-env-slhwwdsz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
> 
>       self.run_setup()
> 
>     File "/tmp/pip-build-env-slhwwdsz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
> 
>       super(_BuildMetaLegacyBackend,
> 
>     File "/tmp/pip-build-env-slhwwdsz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
> 
>       exec(compile(code, __file__, 'exec'), locals())
> 
>     File "setup.py", line 10, in <module>
> 
>       import torch
> 
>   ModuleNotFoundError: No module named 'torch'
> 
>   ----------------------------------------
> 
> WARNING: Discarding git+https://github.com/facebookresearch/detectron2.git. Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmphk82qqi5 Check the logs for full command output.
> 
> ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmphk82qqi5 Check the logs for full command output.
> 
> ```
> 
> 
> 
> However, as @ppwwyyxx identified, there are other limitations that limit the options you have at the moment - ie. you cannot discover automatically the pre-built wheels provided by `detectron2` nor can they distribute CUDA wheels on PyPI.
> 
> 
> 
> For instance, poetry resolver today does not handle local tags well neither does using link repositories work. This means that you cannot use the indices described in https://github.com/facebookresearch/detectron2/blob/main/INSTALL.md#install-pre-built-detectron2. However, you can use the direct links to the wheels here, but this assumes everwhere you install your package the same wheel can be used (this should be fine for cpu, alternatively you can have various extras. This is being fixed (partially done).
> 
> 
> 
> That said, I do not think the python packaging ecosystem has a decent solution for gpu packages anyway - eg. there is no standard way to determine if a cuda enabled wheel can be used in active environment.
> 
> 
> 
> - https://discuss.python.org/t/what-to-do-about-gpus-and-the-built-distributions-that-support-them/7125
> 
> - https://mail.python.org/archives/list/distutils-sig@python.org/thread/LXLF4YSC4WUZOYRX65DW7CESIX7UUBK5/
> 
> 
> 
> Having the dependency metadata specify something like `{ ..., extra-build-requires = ["torch"] }` might be an option, but I am not sure if we should start doing this. On the one hand, this enables poetry users to consume packages where similar issues exist more cleanly (this won't solve the gpu issue), on the other hand this is a workaround for lack of standard metadata.
> 
> 
> 
> Another option is to allow for something like `{ ..., build-allow-system-site = true }`. In this case, the system packages are allowed for package builds.
> 
> 
> 
> What poetry should do in the near future are the following:
> 
> 1. Allow for `--find-link` type sources in projects.
> 
> 2. Support local version tags for dependency resolution and package installation.
> 
> 
> 
> I still think that the `torch` dependency need to be declared in the project's metadata (not in downstream packages) if it is required at build time, so that PEP-517 builds can work correctly.
> 
> 
> 
> As for the gpu specific versions, I am not sure where this needs to go. Ideally, there will be a packaging PEP that will help tools like 'poetry' to implement a standardised approach.

Has this been addressed / solved in the meantime? The standard installation still does not work. But what about the many suggested modifications to poetry that you outlined. Have they been implemented? How can you install detectron2 now with poetry?

**Comment by zengjie617789** [comment]
just using the executable python to run the setup script, like: `cd ../detectron2 && /root/.cache/pypoetry/virtualenvs/image-inpainting-WGCBfPov-py3.10/bin/python setup.py install`
