### ISSUE TITLE
At pyproject.toml file Include section does not respect packages section

### ISSUE THREAD

**Issue by castalheiro** [python-poetry/poetry#3285]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [URL](https://gist.github.com/castalheiro/3c11382feeb9ced789d5987a915aecc5)

## Issue

Projects that do not follow the standard python package structure (e.g. root package inside src directory) require a packages definition as follows:
```
packages = [
    { include = "my_package", from = "src" },
]
```
Under some circumstances it is also be required to create a wheel including files ignored by VCS. And that's where it gets tricky.

The following include section definition doesn't work (and there's no "from" option to fix it.)

```
include = [
    { path = "my_package/*.py"}
]
```
Alternatively, the following definition clashes with the previous packages section definition (the output wheel will contain a src folder instead of the desired my_package directory).

```
include = [
    { path = "src/my_package/*.py"}
]
```

All in all, I'm unable to build the expected package wheel.

**Comment by finswimmer** [comment]
Hello @castalheiro,

thanks for reporting this. I can confirm it.

fin swimmer

**Comment by iamhatesz** [comment]
+1. I can also confirm this behavior in version 1.1.4.

**Comment by audunska** [comment]
We are affected by this. We have some generated protobuf code which is gitignored, but should be included in the wheel, so we use an include directive. But the resulting paths are messed up.

I made a minimal reproducing package here:
https://github.com/audunska/poetry-bug

**Comment by audunska** [comment]
I believe this is now fixed with [poetry-core#124](https://github.com/python-poetry/poetry-core/pull/124) merged.

**Comment by sdispater** [comment]
@audunska It will actually be fixed once there is a new release of `poetry-core` and an accompanying release of Poetry that includes these changes. That's why we'll leave this issue open for now.

**Comment by finswimmer** [comment]
@andrewasheridan : Are you looking for this: https://python-poetry.org/docs/pyproject/#packages ?

**Comment by andrewasheridan** [comment]
@finswimmer wow not sure how I missed that. Thank you

**Comment by gangofnuns** [comment]
Still doesn't seem to work for me.  Using a freshly installed poetry 1.1.13.
Poetry will not recognize the following directive in the pyproject.toml file: 

packages = [
  { include = "bin2ools-rds",  from = "src" },
]

Am I missing something here?  Seems like it should be less complicated, 
like I shouldn't have to explicitly add  the 'src', if that is the defaulat structure.

What am I missing here?

The 'src' parameter isn't recognized, so the corresponding package 
files are build from the *current* dir, instead of the 'src' subdir.  
RESULT:  Package uninstallable.  Files cannot be found.

**Comment by clintonroy** [comment]
@gangofnuns my guess is that it's the hypen in the name, which makes it an invalid package name, try changing that to an underscore (you might have to rename the directory as well, not so sure on that)

**Comment by gangofnuns** [comment]
You are indeed correct -- thanks for the note.  Should have looked a bit
deeper.   Cheers --
