### ISSUE TITLE
Cannot add "Pillow" package dependency through interactive init

### ISSUE THREAD

**Issue by Ivoz** [python-poetry/poetry#3612]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 x64 2004
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  not relevant

## Issue
Hi, I tried to interactively create a new project with some existing python files using `poetry init`. However I found some sad behaviour when trying to interactively specify packages I wanted.

I couldn't add the `Pillow` package. Adding matplotlib worked fine. I think you can see the issue from the terminal output...
```
Search for package to add (or leave blank to continue): matplotlib
Found 20 packages matching matplotlib

Enter package # to add, or the complete package name if it is not listed:
 [0] matplotlib
 [1] jirafs-matplotlib
 [2] matplotlib-helper
 [3] matplotlib-venn
 [4] chineseize-matplotlib
 [5] matplotlib-colorbar
 [6] django-matplotlib
 [7] matplotlib-pgfutils
 [8] matplotlib-stream
 [9] matplotlib-helpers
 > 0
Enter the version constraint to require (or leave blank to use the latest version):
Using version ^3.3.4 for matplotlib

Add a package: Pillow
Found 20 packages matching Pillow

Enter package # to add, or the complete package name if it is not listed:
 [0] Pillow3f
 [1] pillow-lut
 [2] pillow-affine
 [3] pillow-scripts
 [4] pillow-snippet
 [5] pillow-tools
 [6] Pillow-PIL
 [7] pillow-stackblur
 [8] Pillow-SIMD
 [9] images2gif-Pillow
 > pillow
Value "pillow" is invalid

Enter package # to add, or the complete package name if it is not listed:
 [0] Pillow3f
 [1] pillow-lut
 [2] pillow-affine
 [3] pillow-scripts
 [4] pillow-snippet
 [5] pillow-tools
 [6] Pillow-PIL
 [7] pillow-stackblur
 [8] Pillow-SIMD
 [9] images2gif-Pillow
 > Pillow
Value "Pillow" is invalid

Enter package # to add, or the complete package name if it is not listed:
 [0] Pillow3f
 [1] pillow-lut
 [2] pillow-affine
 [3] pillow-scripts
 [4] pillow-snippet
 [5] pillow-tools
 [6] Pillow-PIL
 [7] pillow-stackblur
 [8] Pillow-SIMD
 [9] images2gif-Pillow
 >
(env) C:\Users\Matthew\code\orbits>
```

So confusingly, the normal `Pillow` package was nowhere to be found, and apparently writing the complete package name "Pillow" as instructed is invalid?

I would also like to add that there is no instructions on how to (manually?) *finish* adding package dependencies. I pressed control+C at the end hoping to continue to the next step, but it killed the whole process.

**Comment by sinoroc** [comment]
Looks like a duplicate to me, from memory there already are similar tickets, maybe I'm wrong.

**Comment by teauxfu** [comment]
I'm also having this issue, and was unsuccessful finding a similar ticket.

**Comment by Ivoz** [comment]
> 
> 
> Looks like a duplicate to me, from memory there already are similar tickets, maybe I'm wrong.

If you can find one, please link it, I could not

**Comment by sinoroc** [comment]
https://github.com/python-poetry/poetry/issues/1984

**Comment by sinoroc** [comment]
https://github.com/python-poetry/poetry/issues/3434

**Comment by Ivoz** [comment]
Yes, you could mark this essentially as a duplicate of these two issues.

I am not sure if they mention my last point, that it's also unclear how to exit the dependency-adding process at this point

**Comment by Ivoz** [comment]
It looks like the user message is a "lie", because poetry uses only [the cleo choice function](https://github.com/python-poetry/poetry/blob/6eaa2984d9fb51a837c4ab11643f4dd9d7828d4d/poetry/console/commands/init.py#L288) ([docs](https://cleo.readthedocs.io/en/latest/helpers/question_helper.html#let-the-user-choose-from-a-list-of-answers), [source](https://github.com/sdispater/cleo/blob/9d289bf709ab2119b58e95da58a655ab70661798/cleo/commands/command.py#L173)) which has no such allowance for a non-numeric answer.

I guess the most obvious step is to stop poetry from not finding and priority-listing a direct match name

**Comment by Ivoz** [comment]
Closing, it looks like this issue should be solved by [pull 3470](https://github.com/python-poetry/poetry/pull/3470) if/when it is merged and there are duplicates above

**Comment by Ivoz** [comment]
Not yet merged

**Comment by SpangleLabs** [comment]
Amazed this is still an open issue.

And how do you exit dependency adding? I guessed maybe an empty string, but got 
> `'NoneType' object has no attribute 'replace'`
and then it failed.

**Comment by Secrus** [comment]
> Amazed this is still an open issue.
> 
> And how do you exit dependency adding? I guessed maybe an empty string, but got
> 
> > `'NoneType' object has no attribute 'replace'`
> 
> and then it failed.

@SpangleLabs 
What you are describing seems not exactly related to this issue. You are welcome to open an issue on that.

**Comment by SpangleLabs** [comment]
The second part is a bit different, yeah, apologies.

Initially, I was having the exact same issue of trying to add Pillow, and being amazed it's not one of the suggestions, and then finding that if I type the name, it still doesn't accept it.

**Comment by mkniewallner** [comment]
Duplicate of https://github.com/python-poetry/poetry/issues/3434, which has been closed since the issue appears to have been fixed in [1.2.0b1](https://github.com/python-poetry/poetry/releases/tag/1.2.0b1).

For the other issue mentioned (`'NoneType' object has no attribute 'replace'`), I've just tested on latest version from `master` branch, and it does seem to have been fixed, meaning you can now exit dependency adding by typing an empty choice for the selection, then an empty choice for the package name to go the next question:
```console
Search for package to add (or leave blank to continue): Pillow
Found 20 packages matching Pillow
Showing the first 10 matches

Enter package # to add, or the complete package name if it is not listed []:
 [ 0] Pillow
 [ 1] Pillow3f
 [ 2] pillow-lut
 [ 3] pillow-mbm
 [ 4] pillow-jpls
 [ 5] Pillow-PIL
 [ 6] pillow-affine
 [ 7] pyme-pillow
 [ 8] pillow-heif
 [ 9] pillow-scripts
 [10] 
 > 
No package selected

Add a package:

Would you like to define your development dependencies interactively? (yes/no) [yes]
```
