### ISSUE TITLE
Adding a private repo via ssh fails, while same repo works via pip install

### ISSUE THREAD

**Issue by ipsingh06** [python-poetry/poetry#5152]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not applicable

## Issue

Adding a private repo via ssh fails.
```
poetry add git+ssh://git@github.com/org/privaterepo.git

  CalledProcessError

  Command '['git', '--git-dir', '/tmp/pypoetry-git-reposm6ni0d2/.git', '--work-tree', '/tmp/pypoetry-git-reposm6ni0d2', 'checkout', 'master']' returned non-zero exit status 1.

  at ~/.poetry/lib/poetry/utils/_compat.py:217 in run
      213?                 process.wait()
      214?                 raise
      215?             retcode = process.poll()
      216?             if check and retcode:
    ? 217?                 raise CalledProcessError(
      218?                     retcode, process.args, output=stdout, stderr=stderr
      219?                 )
      220?         finally:
      221?             # None because our context manager __exit__ does not use them.

```

Installing via `pip install` works fine.
```
pip install git+ssh://git@github.com/org/privaterepo.git
```

**Comment by finswimmer** [comment]
Hello @ipsingh06,

I guess the default branch of your is not called `master`. But the current stable release assumes this. This is fixed in the current preview release.

fin swimmer

**Comment by ipsingh06** [comment]
Hey @finswimmer .

I can confirm that I see the same error with Poetry version `1.2.0a2`.

**Comment by devRMA** [comment]
> Hello @ipsingh06,
> 
> I guess the default branch of your is not called `master`. But the current stable release assumes this. This is fixed in the current preview release.
> 
> fin swimmer

I was having this same error, and it really is because of the ``master`` branch.
My ``pyproject.toml`` that was giving error was like this
```toml
# ...

[tool.poetry.dependencies]
python = "^3.10"
"python-stopwatch" = {git = "https://github.com/devRMA/python-stopwatch.git"}
```
I just added the main branch, and it solved the error
```toml
# ...

[tool.poetry.dependencies]
python = "^3.10"
"python-stopwatch" = {git = "https://github.com/devRMA/python-stopwatch.git", branch = "main"}
```

**Comment by shelper** [comment]
I think this is still not working

i have a repo i can clone through ssh 
but cannot install using poetry (even with latest 1.3.2)
just got error like below

`poetry add git+ssh://git@github.com:user/repo_name.git#main
`
```
Package operations: 1 install, 0 updates, 0 removals

  - Installing repo_name (0.1.0 8533235)

Failed to install /home/username/.cache/pypoetry/virtualenvs/zetta-oJ7qmDvX-py3.8/src/repo_name
```
