### ISSUE TITLE
Pip raising error on installing when specifying an extra

### ISSUE THREAD

**Issue by tigerhawkvok** [python-poetry/poetry#5842]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Build: Windows 10; Deploy: Databricks on AWS
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/tigerhawkvok/2151fc568ef5af8bcbf1326985d26655

## Issue
Trying to install, Pip throws an error

```
Traceback (most recent call last):
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/pyparsing.py", line 1955, in parseString
    raise exc
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd, found 'e'  (at char 62), (line:1, col:63)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3101, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 115, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'extra =='": Expected stringEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 347, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in get_dependencies
    return [
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in <listcomp>
    return [
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 251, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2736, in requires
    dm = self._dep_map
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3033, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "/local_disk0/pythonVirtualEnvDirs/virtualEnv-ec62d82e-1faa-47c3-a603-ba3467e54cbf/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Parse error at "'extra =='": Expected stringEnd
```

Seems that with an extra (possibly just a path extra?)  pip is unhappy. Filesize implies the extra isn't vendored in. While I have a URL, due to network policy there may or may not be issues pulling from the URL, so I'd _very_ much prefer retaining the path dependency.

**Comment by dimbleby** [comment]
cannot reproduce, even at 1.1.13.

(I took gdal out of the pyproject.toml 'cos I can't be bothered with figuring out the dependencies for that, so maybe that's where the issue is?)

You seem to have cut the log short, perhaps the full log makes it clearer what package it is dealing with when it reckons that it encounters the string `'extra =='`?

**Comment by dimbleby** [comment]
Ah, you didn't say so, but what you mean is: 

- you have run `poetry build` 
- you are now trying to `pip install` the resulting wheel

and this is a duplicate of #2802

**Comment by tigerhawkvok** [comment]
The log is a little short because it's wrapped by a scala -> py4j error; the rest of the message is java insane namespace messages for failing the Python invocation. I worked around it by cutting that out, and this particular issue was between commits, but here is a similar message:


```
Python interpreter will be restarted.
Processing /dbfs/FileStore/jars/026d5f54_ecb7_4483_8269_d18b33307512/pyhelpers-1.9.3-py3-none-any.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/pyparsing.py", line 1955, in parseString
    raise exc
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd, found 'p'  (at char 46), (line:1, col:47)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3101, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 115, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'platform'": Expected stringEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 347, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in get_dependencies
    return [
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 170, in <listcomp>
    return [
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 251, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2736, in requires
    dm = self._dep_map
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3033, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-fa9cd7d2-c35a-4f17-b4cc-96044f7fc642/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Parse error at "'platform'": Expected stringEnd
```




Fwiw, the grosser specification for gdal that I simplified for upload was

```
gdal = [
    {version = "3.3", markers= "platform_system != 'Windows'"}, # Ubuntu: requires `sudo apt-get update && sudo apt-get install gdal-bin libgdal-dev python3-gdal -y` to be run first. May need to be manually set to 3.0.4
    {path = "GDAL-3.3.1-cp38-cp38-win_amd64.whl", python = "~3.8.0", markers= "platform_system == 'Windows'"}
]
fiona = [
    {version = "^1.0.0", markers= "platform_system != 'Windows'"},
    {path = "Fiona-1.8.20-cp38-cp38-win_amd64.whl", python = "~3.8.0", markers= "platform_system == 'Windows'"}
]
```

It's kind of similar to #2802 but that said it was fixed back in 2020 in version 1.0.0b1

**Comment by dimbleby** [comment]
well maybe there was another similar.  I have verified that with recent poetry we get a wheel that contains `METADATA` with a space before the semi-colon:
```
Requires-Dist: databricks-mosaic @ databricks_mosaic-0.1.1-py3-none-any.whl ; extra == "mosaic"
```
and that of course pip refuses to install this because what sort of a url is that?

```
...
   raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid URL given
```

ie your bug is already fixed, but what you are trying to do cannot work

**Comment by tigerhawkvok** [comment]
Hah, looks like we're visiting this at the same time.

> Though NB even then I wouldn't bet on this working, I think you will find that a wheel built to reference a local file will not go well

I think I figured out that was part of it (though that parsing error still shouldn't happen in 1.1.13, so I think the issue stands). I can make it work for my immediate use case by commenting that part out of pyproject.toml .

(The local file issue I commented on https://github.com/python-poetry/poetry/issues/2828#issuecomment-1154323769 as a support for vendored dependencies)

**Comment by dimbleby** [comment]
crossing coments again: but per my last the issue that causes the parsing error is not still present, this should be good to close
