### ISSUE TITLE
Infinite loop at install time, with tracked down reason

### ISSUE THREAD

**Issue by lelit** [python-poetry/poetry#5982]
### Discussed in https://github.com/python-poetry/poetry/discussions/5936

<div type='discussions-op-text'>

<sup>Originally posted by **lelit** June 30, 2022</sup>
I'm seeking an advice on how to investigate, and hopefully resolve, a problem I hit today.

The following very simple `pyproject.toml`, created with `poetry init` (v1.1.13), has a single dependency against a project of mine:
```toml
[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["Lele Gaifax <lele@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
metapensiero-tool-tinject = "^1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Executing `poetry install` enters into an infinite loop, and with `-vvv` I can see:
```
Using virtualenv: /tmp/e
Updating dependencies
Resolving dependencies...
   1: fact: foo is 0.1.0
   1: derived: foo
   1: fact: foo depends on metapensiero-tool-tinject (^1.0)
   1: selecting foo (0.1.0)
   1: derived: metapensiero-tool-tinject (>=1.0,<2.0)
   1: fact: metapensiero-tool-tinject (1.0) depends on jinja2 (*)
   1: fact: metapensiero-tool-tinject (1.0) depends on jinja2-time (*)
   1: fact: metapensiero-tool-tinject (1.0) depends on questionary (*)
   1: fact: metapensiero-tool-tinject (1.0) depends on ruamel-yaml (*)
   1: selecting metapensiero-tool-tinject (1.0)
   1: derived: ruamel-yaml
   1: derived: questionary
   1: derived: jinja2-time
   1: derived: jinja2
   1: fact: jinja2-time (0.2.0) depends on jinja2 (*)
   1: fact: jinja2-time (0.2.0) depends on arrow (*)
   1: selecting jinja2-time (0.2.0)
   1: derived: arrow
   1: fact: questionary (1.10.0) depends on prompt_toolkit (>=2.0,<4.0)
   1: selecting questionary (1.10.0)
   1: derived: prompt_toolkit (>=2.0,<4.0)
   1: fact: prompt-toolkit (3.0.30) depends on wcwidth (*)
   1: selecting prompt-toolkit (3.0.30)
   1: derived: wcwidth
   1: selecting wcwidth (0.2.5)
   1: fact: jinja2 (3.1.2) depends on MarkupSafe (>=2.0)
   1: selecting jinja2 (3.1.2)
   1: derived: MarkupSafe (>=2.0)
   1: selecting markupsafe (2.1.1)
   1: fact: arrow (1.2.2) depends on python-dateutil (>=2.7.0)
   1: selecting arrow (1.2.2)
   1: derived: python-dateutil (>=2.7.0)
   1: fact: python-dateutil (2.8.2) depends on six (>=1.5)
   1: selecting python-dateutil (2.8.2)
   1: derived: six (>=1.5)
   1: selecting six (1.16.0)
   1: fact: ruamel.yaml (0.17.21) depends on ruamel.yaml.clib (>=0.2.6)
   1: selecting ruamel.yaml (0.17.21)
   1: fact: ruamel.yaml (0.17.21) depends on ruamel.yaml.clib (>=0.2.6)
   1: selecting ruamel.yaml (0.17.21)
   1: fact: ruamel.yaml (0.17.21) depends on ruamel.yaml.clib (>=0.2.6)
   1: selecting ruamel.yaml (0.17.21)
   ...
```

The same configuration works with `poetry 1.2.0b2`:
```
Using virtualenv: /tmp/poetry120b2
Project environment contains an empty path in sys_path, ignoring.
Updating dependencies
Resolving dependencies...
   1: fact: foo is 0.1.0
   1: derived: foo
   1: fact: foo depends on metapensiero-tool-tinject (^1.0)
   1: selecting foo (0.1.0)
   1: derived: metapensiero-tool-tinject (>=1.0,<2.0)
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/metapensiero-tool-tinject/json HTTP/1.1" 200 8155
Source (PyPI): No release information found for metapensiero-tool-tinject-0.0, skipping
Source (PyPI): 1 packages found for metapensiero-tool-tinject >=1.0,<2.0
Source (PyPI): Getting info for metapensiero-tool-tinject (1.0) from PyPI
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/metapensiero-tool-tinject/1.0/json HTTP/1.1" 200 8155
   1: fact: metapensiero-tool-tinject (1.0) depends on jinja2 (*)
   1: fact: metapensiero-tool-tinject (1.0) depends on jinja2-time (*)
   1: fact: metapensiero-tool-tinject (1.0) depends on questionary (*)
   1: fact: metapensiero-tool-tinject (1.0) depends on ruamel-yaml (*)
   1: selecting metapensiero-tool-tinject (1.0)
   1: derived: ruamel-yaml
   1: derived: questionary
   1: derived: jinja2-time
   1: derived: jinja2
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/ruamel-yaml/json HTTP/1.1" 200 330382
Source (PyPI): 236 packages found for ruamel-yaml *
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/questionary/json HTTP/1.1" 200 8296
Source (PyPI): 18 packages found for questionary *
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/jinja2-time/json HTTP/1.1" 200 2918
Source (PyPI): 2 packages found for jinja2-time *
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/jinja2/json HTTP/1.1" 200 15028
Source (PyPI): 44 packages found for jinja2 *
Source (PyPI): Getting info for jinja2-time (0.2.0) from PyPI
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/jinja2-time/0.2.0/json HTTP/1.1" 200 2918
Source (PyPI): No dependencies found, downloading archives
Source (PyPI): Downloading wheel: jinja2_time-0.2.0-py2.py3-none-any.whl
Creating new session for files.pythonhosted.org
[urllib3.connectionpool] Starting new HTTPS connection (1): files.pythonhosted.org:443
[urllib3.connectionpool] https://files.pythonhosted.org:443 "GET /packages/6a/a1/d44fa38306ffa34a7e1af09632b158e13ec89670ce491f8a15af3ebcb4e4/jinja2_time-0.2.0-py2.py3-none-any.whl HTTP/1.1" 200 6360
   1: fact: jinja2-time (0.2.0) depends on jinja2 (*)
   1: fact: jinja2-time (0.2.0) depends on arrow (*)
   1: selecting jinja2-time (0.2.0)
   1: derived: arrow
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/arrow/json HTTP/1.1" 200 16812
Source (PyPI): 62 packages found for arrow *
Source (PyPI): Getting info for questionary (1.10.0) from PyPI
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/questionary/1.10.0/json HTTP/1.1" 200 8296
   1: fact: questionary (1.10.0) depends on prompt_toolkit (>=2.0,<4.0)
   1: selecting questionary (1.10.0)
   1: derived: prompt_toolkit (>=2.0,<4.0)
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/prompt-toolkit/json HTTP/1.1" 200 39862
Source (PyPI): 41 packages found for prompt-toolkit >=2.0,<4.0
Source (PyPI): Getting info for prompt-toolkit (3.0.30) from PyPI
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/prompt-toolkit/3.0.30/json HTTP/1.1" 200 39862
   1: fact: prompt-toolkit (3.0.30) depends on wcwidth (*)
   1: selecting prompt-toolkit (3.0.30)
   1: derived: wcwidth
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/wcwidth/json HTTP/1.1" 200 9186
Source (PyPI): 17 packages found for wcwidth *
Source (PyPI): Getting info for wcwidth (0.2.5) from PyPI
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/wcwidth/0.2.5/json HTTP/1.1" 200 9186
   1: selecting wcwidth (0.2.5)
Source (PyPI): Getting info for jinja2 (3.1.2) from PyPI
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/jinja2/3.1.2/json HTTP/1.1" 200 15028
   1: fact: jinja2 (3.1.2) depends on MarkupSafe (>=2.0)
   1: selecting jinja2 (3.1.2)
   1: derived: MarkupSafe (>=2.0)
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/markupsafe/json HTTP/1.1" 200 52932
Source (PyPI): 4 packages found for markupsafe >=2.0
Source (PyPI): Getting info for markupsafe (2.1.1) from PyPI
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/markupsafe/2.1.1/json HTTP/1.1" 200 52932
Source (PyPI): No dependencies found, downloading archives
Source (PyPI): Downloading sdist: MarkupSafe-2.1.1.tar.gz
[urllib3.connectionpool] https://files.pythonhosted.org:443 "GET /packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz HTTP/1.1" 200 18668
   1: selecting markupsafe (2.1.1)
   1: fact: arrow (1.2.2) depends on python-dateutil (>=2.7.0)
   1: selecting arrow (1.2.2)
   1: derived: python-dateutil (>=2.7.0)
   1: fact: python-dateutil (2.8.2) depends on six (>=1.5)
   1: selecting python-dateutil (2.8.2)
   1: derived: six (>=1.5)
   1: selecting six (1.16.0)
   1: fact: ruamel-yaml (0.17.21) depends on ruamel.yaml.clib (>=0.2.6)
   1: selecting ruamel-yaml (0.17.21)
   1: derived: ruamel.yaml.clib (>=0.2.6)
   1: selecting ruamel-yaml-clib (0.2.6)
   1: Version solving took 26.670 seconds.
   1: Tried 1 solutions.

Finding the necessary packages for the current system

Package operations: 11 installs, 0 updates, 0 removals, 1 skipped

  • Installing markupsafe (2.1.1)
  • Installing markupsafe (2.1.1)
  • Installing python-dateutil (2.8.2)
  • Installing python-dateutil (2.8.2)
  • Installing wcwidth (0.2.5)
  • Installing wcwidth (0.2.5)
  • Installing arrow (1.2.2)
  • Installing arrow (1.2.2)
  • Installing jinja2 (3.1.2)
  • Installing jinja2 (3.1.2)
  • Installing prompt-toolkit (3.0.30)
  • Installing prompt-toolkit (3.0.30)
  • Installing ruamel-yaml-clib (0.2.6)
  • Installing ruamel-yaml-clib (0.2.6)
  • Installing jinja2-time (0.2.0)
  • Installing questionary (1.10.0)
  • Installing ruamel-yaml (0.17.21)
  • Installing questionary (1.10.0)
  • Installing jinja2-time (0.2.0)
  • Installing ruamel-yaml (0.17.21)
  • Installing metapensiero-tool-tinject (1.0)
  • Installing metapensiero-tool-tinject (1.0)
  • Installing six (1.16.0): Skipped for the following reason: Already installed
```

Apparently the problem is related to a new 1.0 release of [metapensiero.tool.tinject](https://pypi.org/project/metapensiero-tool-tinject/) that I made yesterday, but I really cannot understand what I did wrong to break poetry resolver :sob:. The fact that both `pip` and `poetry 1.2.0b2` correctly install it seems to suggest that the package is correct...

I'd appreciate any hint on how to proceed.

Thanks in advance!
</div>

**Comment by lelit** [comment]
In [this comment](https://github.com/python-poetry/poetry/discussions/5936#discussioncomment-3113135)` I expose an analysis of the problem, solvable by backporting [this commit](https://github.com/python-poetry/poetry-core/commit/259bbbe50692346ecf9445b1114a9c740f5b89af) to `poetry-core` 1.0.x.

**Comment by dimbleby** [comment]
there won't be back-application to poetry-core 1.0, this is fixed on master (main in poetry-core) and can be closed as such

**Comment by lelit** [comment]
Ok, thanks. Does that mean that poetry 1.1 will never cope with this issue?

**Comment by dimbleby** [comment]
that would be my expectation

**Comment by mkniewallner** [comment]
Hi, we indeed don't plan to backport fixes to poetry `1.1` branch, nor poetry-core `1.0` branch, since 1.2.0 is around the corner.

We understand this is not an ideal situation, but we have limited resources, and would rather put them on getting 1.2.0 released.

In the meantime, you still have the ability to use [1.2.0b3](https://github.com/python-poetry/poetry/releases/tag/1.2.0b3), which is in a pretty usable state, despite being a beta.
