### ISSUE TITLE
poetry-core does not execute `build` function in `build.py`

### ISSUE THREAD

**Issue by cdgriffith** [python-poetry/poetry#7470]
- **Poetry version**:  1.3.2
- **Python version**: 3.10.9
- **OS version and name**: Windows 11
- **pyproject.toml**: [](https://gist.github.com/cdgriffith/87f90be0e9d58ca6e53ac64522816908)

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Trying to switch to the lighter `poetry-core` for building wheels, but the `build` function is not executed inside the `build.py` file.

Using `poetry.core` as the build backend, I will only see `Build File Imported` (custom print statements in `build.py`) and neither `build` function is called.

However if I switch the build system back to the old method of just `poetry`: 

```
[build-system]
requires = ["poetry", "Cython", "setuptools", "wheel"]
build-backend = "poetry.masonry.api"
```

Everything will work fine when I run `pip wheel . -v` and show both:

```
Build File Imported
Build with Cython
```

`build.py`

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
from setuptools.command.build_ext import build_ext

from pathlib import Path
import shutil

root = Path(__file__).parent

print("Build File Imported")

def copy_files():
    # Why does poetry put include files at the root of site-packages? So bad! Copy them inside the package
    shutil.copy(root / "AUTHORS.rst", root / "box" / "AUTHORS.rst")
    shutil.copy(root / "CHANGES.rst", root / "box" / "CHANGES.rst")
    shutil.copy(root / "LICENSE", root / "box" / "LICENSE")
    shutil.copy(root / "box_logo.png", root / "box" / "box_logo.png")


try:
    from Cython.Build import cythonize
except ImportError:
    # Got to provide this function. Otherwise, poetry will fail
    def build(setup_kwargs):
        print("Build without Cython")
        copy_files()


# Cython is installed. Compile
else:
    # This function will be executed in setup.py:
    def build(setup_kwargs):
        print("Build with Cython")
        copy_files()
        # Build
        setup_kwargs.update(
            {
                "ext_modules": cythonize(
                    [
                        str(file.relative_to(root))
                        for file in Path(root, "box").glob("*.py")
                        if file.name != "__init__.py"
                    ],
                    compiler_directives={"language_level": 3},
                ),
            }
        )

```

Package itself is https://github.com/cdgriffith/Box/blob/master/pyproject.toml and issue brought up by https://github.com/cdgriffith/Box/pull/244

**Comment by dimbleby** [comment]
probably broken by https://github.com/python-poetry/poetry-core/pull/318, try
```toml
[tool.poetry.build]
script = "build.py"
generate-setup-file = true
```

**Comment by cdgriffith** [comment]
That does allow it to work! 

Does create a unwanted setup.py file. Is this simply new behavior, or will this be something fixed in later versions, that poetry-core will be able to call `build`?

**Comment by dimbleby** [comment]
setting this explicitly is simply restoring the old behaviour - the default changed

**Comment by cdgriffith** [comment]
Got ya, thank you for the fast help @dimbleby !

**Comment by JacobHayes** [comment]
I think the old
```toml
[tool.poetry]
build = "build.py"
```
behaves differently than
```toml
[tool.poetry.build]
script = "build.py"
generate-setup-file = true
```

The old method _would_ include generated shared objects in the built wheels, however a wheel built with `[tool.poetry.build]` **will be missing shared objects**. I confirmed that by running the following snippet with a package using Cython for both styles of config:
```
$ rm src/{**/,}*.cpython-*.so # Delete cython generated .cpython-*.so files
$ rm -rf build/ dist/
$ poetry build -f wheel
$ strings dist/*.whl | grep '\.cpython.*.so'  # Output for `build = `, no output for `script = `
```

---

Is this intentional or perhaps an accidental change? (it does seem to still occur in 1.4.0, so I don't think it's a 1.5.0 only issue)

**Comment by jcampbell05** [comment]
@dimbleby  is there a plan to make a more stable API around this ? I've started building a plugin to try to handle Cython building like this.

The fact it's an unstable API at the moment makes it unfortunately more work to rely on this behaviour as understandable change-logs won't mention behaviour changes like this.

**Comment by dimbleby** [comment]
#2740
