### ISSUE TITLE
Installing a package that depends on setuptools fails intermittently: `Backend 'setuptools.build_meta:__legacy__' is not available.`

### ISSUE THREAD

**Issue by MycroftKang** [python-poetry/poetry#7611]
- **Poetry version**: 1.4.0
- **Python version**: 3.10.9
- **OS version and name**: Microsoft Windows Server 2022 10.0.20348 Datacenter (`windows-2022` GitHub runner)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Installing a package that depends on setuptools fails intermittently. This bug does not occur in poetry 1.3 and is found in poetry 1.4.

```
ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.

  at C:\Program Files (x86)\pipx\venvs\poetry\lib\site-packages\poetry\installation\chef.py:152 in _prepare
      148| 
      149|                 error = ChefBuildError("\n\n".join(message_parts))
      150| 
      151|             if error is not None:
    > 152|                 raise error from None
      153| 
      154|             return path
      155| 
      156|     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with docopt (0.6.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "docopt (==0.6.2)"'.
```

<details>
<summary>View full logs</summary>
<pre><code>
    $ poetry install
    Installing dependencies from lock file

    Package operations: 150 installs, 2 updates, 0 removals

        Installing certifi (2022.12.7)
        Installing charset-normalizer (2.0.12)
        Installing idna (3.4)
        Installing pyasn1 (0.4.8)
        Installing urllib3 (1.26.14)
        Installing cachetools (5.3.0)
        Installing oauthlib (3.2.2)
        Installing pyasn1-modules (0.2.8)
        Installing requests (2.28.2)
        Installing six (1.16.0)
        Installing rsa (4.9)
        Installing catalogue (2.0.8)
        Installing colorama (0.4.6)
        Installing google-auth (2.16.0)
        Installing markupsafe (2.1.2)
        Installing requests-oauthlib (1.3.1)
        Installing multidict (5.2.0)
        Installing typing-extensions (4.4.0)
        Installing tzdata (2022.7)
        Installing absl-py (1.3.0)
        Installing click (8.1.3)
        Installing cymem (2.0.7)
        Installing frozenlist (1.3.3)
        Installing grpcio (1.51.1)
        Installing google-auth-oauthlib (0.4.6)
        Installing locket (1.0.0)
        Installing markdown (3.4.1)
        Installing murmurhash (1.0.9)
        Installing numpy (1.23.5)
        Installing pamqp (3.2.1)
        Installing protobuf (3.19.6)
        Installing pydantic (1.10.4)
        Installing pyparsing (3.0.9)
        Installing pyreadline3 (3.4.1)
        Installing pytz-deprecation-shim (0.1.0.post0)
        Installing ruamel-yaml-clib (0.2.7)
        Updating setuptools (65.3.0 -> 66.1.1)
        Installing srsly (2.4.5)
        Installing tensorboard-data-server (0.6.1)
        Installing tensorboard-plugin-wit (1.8.1)
        Installing termcolor (2.2.0)
        Installing toolz (0.12.0)
        Installing werkzeug (2.2.2)
        Updating wheel (0.37.1 -> 0.38.4)
        Installing yarl (1.8.2)
        Installing aiormq (6.6.4)
        Installing aiosignal (1.3.1)
        Installing astunparse (1.6.3)
        Installing async-timeout (4.0.2)
        Installing attrs (22.1.0)
        Installing blis (0.7.9)
        Installing cloudpickle (2.2.1)
        Installing confection (0.0.4)
        Installing docopt (0.6.2)
        Installing fire (0.5.0)
        Installing flatbuffers (23.1.21)
        Installing fsspec (2023.1.0)
        Installing gast (0.5.3)
        Installing google-pasta (0.2.0)
        Installing greenlet (2.0.1)
        Installing h5py (3.8.0)
        Installing humanfriendly (10.0)
        Installing joblib (1.2.0)
        Installing keras (2.8.0)
        Installing keras-preprocessing (1.1.2)
        Installing libclang (15.0.6.1)
        Installing msgpack (1.0.4)
        Installing opt-einsum (3.3.0)
        Installing packaging (20.9)
        Installing partd (1.3.0)
        Installing preshed (3.0.8)
        Installing pyrsistent (0.19.3)
        Installing python-crfsuite (0.9.9)
        Installing python-dateutil (2.8.2)
        Installing pytz (2022.1)
        Installing pyyaml (6.0)
        Installing ruamel-yaml (0.17.21)
        Installing scipy (1.8.1)
        Installing smart-open (6.3.0)
        Installing tabulate (0.9.0)
        Installing tensorboard (2.8.0)
        Installing tensorflow-estimator (2.8.0)
        Installing tensorflow-io-gcs-filesystem (0.30.0)
        Installing threadpoolctl (3.1.0)
        Installing tqdm (4.64.1)
        Installing typeguard (2.13.3)
        Installing typer (0.7.0)
        Installing tzlocal (4.2)
        Installing wasabi (0.10.1)
        Installing wrapt (1.14.1)

      ChefBuildError

      Backend 'setuptools.build_meta:__legacy__' is not available.

      at C:\Program Files (x86)\pipx\venvs\poetry\lib\site-packages\poetry\installation\chef.py:152 in _prepare
          148| 
          149|                 error = ChefBuildError("\n\n".join(message_parts))
          150| 
          151|             if error is not None:
        > 152|                 raise error from None
          153| 
          154|             return path
          155| 
          156|     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

    Note: This error originates from the build backend, and is likely not a problem with poetry but with docopt (0.6.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "docopt (==0.6.2)"'.
</code></pre>
</details>

## Interim Solutions
There are several workarounds below that mitigate this issue.

* Downgrade poetry version to 1.3
```
pipx install "poetry>=1.3.0,<1.4.0"
```

* Try `poetry install` several times
```
poetry install -vvv --no-root || poetry install -vvv --no-root || poetry install -vvv --no-root...
```

**Comment by dimbleby** [comment]
you didn't provide any means to reproduce.  installing docopts works fine for me.

If you can reproduce then this probably wants reporting to https://github.com/pypa/build/, that's 1.4.0's "modern installer" uses.

**Comment by MycroftKang** [comment]
@dimbleby It doesn't seem to be a problem specific to the docopt package. Installation of the timeout-decorator package fails in the following cases:
* https://github.com/requests-cache/requests-cache/actions/runs/4309110823/jobs/7517583482

Another instance of this bug was reported in: https://github.com/requests-cache/requests-cache/issues/797

**Comment by dimbleby** [comment]
sure, that's all consistent with it being a problem only with the "modern installer" in poetry 1.4.0: and if so then, as above, it likely wants reporting to https://github.com/pypa/build/

**Comment by MycroftKang** [comment]
@sdispater As per https://github.com/python-poetry/poetry/issues/7611#issuecomment-1455818406, this bug seems to be caused by https://github.com/python-poetry/poetry/pull/6205. Could you please follow up on this?

**Comment by Samreay** [comment]
For another case of this (if it helps reproduction), our `pyproject.toml` includes a dependency which installs `pdpyras`.

When running a `poetry install`, we receive:

```bash
ChefBuildError
  Backend 'setuptools.build_meta:__legacy__' is not available.
  at /usr/local/lib/python3.9/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
Note: This error originates from the build backend, and is likely not a problem with poetry but with pdpyras (4.5.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pdpyras (==4.5.2) ; python_version >= "3.5""'.
```

And I can confirm that if I run the command suggested, pdpyras installs perfectly fine.

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/6748505/223877497-6572f521-59b4-426e-9b70-0bc2e20fd222.png">

**Comment by jrversteegh** [comment]
confirm for pluginbase-1.0.1. Works with poetry < 1.4.0, but not with poetry 1.4.0. Same error message.

**Comment by radoering** [comment]
I tried to reproduce this issue by putting all mentioned packages into one pyproject.toml:
```
docopt = "0.6.2"
pdpyras = "4.5.2"
timeout-decorator = "0.5.0"
pytest-clarity = "1.0.1"
pluginbase = "1.0.1"
```

While I have not been able to reproduce the error message mentioned in this issue, I encountered a different issue: pypa/virtualenv#2516

I don't expect it to be related to this issue, but since a new virtualenv version (20.21.0) with a fix was released yesterday, you may want to try to update virtualenv in your poetry installation and confirm that this issue is still present.

Note: The new virtualenv version cannot be used if poetry is installed with Python 3.9 on Windows, see https://github.com/python-poetry/poetry/blob/0e72a55c43a993ec0258facec23416c9212964ba/pyproject.toml#L80-L84

**Comment by alexhermida** [comment]
Same behaviour here with `scikit-learn`, with Poetry 1.3.2 works fine.

**Comment by ElSaico** [comment]
For those experiencing this issue: **update your lock files**. It might've been luck, but mine had as slightly older version of `setuptools` (65.5.0) and upgrading made it behave again.
That would explain the inability to reproduce this bug as well.

**Comment by MusicScience37** [comment]
For some libraries, change of the version of Python resolved errors.

**Comment by aspcompiler** [comment]
We encounter this sporadically with Poetry 1.4.1 running in Windows container as well. The error message is like:

```
 • Installing wrapt (1.14.1)
  ChefBuildError
  Backend 'setuptools.build_meta:__legacy__' is not available.
  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
Note: This error originates from the build backend, and is likely not a problem with poetry but with atomicwrites (1.4.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "atomicwrites (==1.4.1)"'.
```

**Comment by alexjc** [comment]
This happens quite often (not quite reliably) with Python 3.9 on windows, Poetry 1.4.1.  Installing wcwidth as a dependency...

**Comment by gpongelli** [comment]
happened today with a package that has "bs4" as its dependency, when running windows with python 3.8 and 3.9, using poetry 1.4.1 due to recent poetry-core fix.

```
    ChefBuildError
  
    Backend 'setuptools.build_meta:__legacy__' is not available.
  
    at ~\AppData\Local\Temp\cibw-run-fwneq3zj\cp38-win_amd64\venv-test\lib\site-packages\poetry\installation\chef.py:152 in _prepare
        148│ 
        149│                 error = ChefBuildError("\n\n".join(message_parts))
        150│ 
        151│             if error is not None:
      → 152│                 raise error from None
        153│ 
        154│             return path
        155│ 
        156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
  
  Note: This error originates from the build backend, and is likely not a problem with poetry but with bs4 (0.0.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "bs4 (==0.0.1)"'.
```

**Comment by Real-Gecko** [comment]
MacOS Catalina, Python 3.10.11, Poetry 1.4.1
```
  • Installing promise (2.3): Failed

  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.
```

**Comment by radoering** [comment]
To make sure this is not an issue that is fixed in the latest `virtualenv` version, please report the _version of virtualenv in poetry's own environment_ in addition to the operating system and the Python version if you experience this issue!

I am not aware of any universally applicable way to determine the version. If installed poetry via pipx, it should be as easy as running:

```
pipx runpip poetry show virtualenv
```

Otherwise, you probably have to search for poetry's environment manually. If you think, you are in the correct environment, you can run the following snippet:
```
try:
    import poetry
except:
    print("I am not in the poetry environment and this is not the right answer")

import virtualenv
print(virtualenv.__version__)
```

**Comment by thiagobenine** [comment]
> For those experiencing this issue: **update your lock files**. It might've been luck (intermittent failure and all...), but here it started to behave again.[1] That would explain the inability to reproduce this bug as well.
> 
> [1] ...and then immediately stumble into #7572, as I'm using Hypercorn, but that one is better understood and can be worked around without downgrading.

Updating the `lock` files solved for me, thanks @gpongelli!

**Comment by ancalita** [comment]
We've also noticed this in the CI on Windows jobs across python 3.8, 3.9, 3.10 after upgrading poetry to `1.4.2`:

```
ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\chef.py:152 in _prepare
      148| 
      149|                 error = ChefBuildError("\n\n".join(message_parts))
      150| 
      151|             if error is not None:
    > 152|                 raise error from None
      153| 
      154|             return path
      155| 
      156|     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with fire (0.5.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "fire (==0.5.0)"'.

  � Installing sanic-cors (2.0.1)
  � Installing scipy (1.8.1)
  � Installing tabulate (0.9.0)
  � Installing tensorboard (2.11.2)
  � Installing tensorflow-estimator (2.11.0)

  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\chef.py:152 in _prepare
      148| 
      149|                 error = ChefBuildError("\n\n".join(message_parts))
      150| 
      151|             if error is not None:
    > 152|                 raise error from None
      153| 
      154|             return path
      155| 
      156|     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with future (0.18.3) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "future (==0.18.3)"'.

```

Confirming the lock file was updated after poetry upgrade with `poetry lock --no-update` and the issue occurs despite this.

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry/issues/7611#issuecomment-1501539967

**Comment by shyney7** [comment]
Same with version 1.4.2

![Screenshot 2023-04-14 095144](https://user-images.githubusercontent.com/17785769/231980493-97d4fd60-b6de-475c-a3c8-19e3aeddacda.png)

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry/issues/7611#issuecomment-1501539967

**Comment by ancalita** [comment]
@dimbleby I can't verify the version of `virtualenv` in the CI pipeline on Windows OS.
However when I ran `poetry self update 1.4.2` on my macOS machine, I noticed that `virtualenv` was downgraded from v`20.16.5` to v`20.16.4`.

**Comment by gpongelli** [comment]
those are two github action that shows the error: https://github.com/gpongelli/pycode128/actions/runs/4587661968/jobs/8101337292 and https://github.com/gpongelli/pycode128/actions/runs/4585602238/jobs/8097847571 .

The issue happens only on windows with python 3.9 , `virtualenv-20.16.5` is installed by cibuildwheel and seems it's cached (I don't know how are cached python packages within github action's execution).

I've solved removing the dependent package that uses bs4 as its own dependency.

**Comment by jouve** [comment]
```
Updating dependencies
Resolving dependencies... (4.7s)

Package operations: 12 installs, 0 updates, 0 removals

  • Installing flatdict (4.0.1): Failed

  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.

  at /usr/local/Cellar/poetry/1.4.2/libexec/lib/python3.11/site-packages/poetry/installation/chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with flatdict (4.0.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "flatdict (==4.0.1)"'.
```

but when I run `pip wheel --use-pep517 "flatdict (==4.0.1)"` , it works 
``` 
CURL_CA_BUNDLE=~/work/cacert/cacert.pem poetry run pip wheel --use-pep517 "flatdict (==4.0.1)"
Collecting flatdict==4.0.1
  Using cached flatdict-4.0.1-py3-none-any.whl
Saved ./flatdict-4.0.1-py3-none-any.whl
```

**Comment by earshinov** [comment]
In our CI I now retry `poetry install` 3 times and it works.

```
RUN (poetry install -vvv --no-root || poetry install -vvv --no-root || poetry install -vvv --no-root)...
```

**Comment by Deuchnord** [comment]
I have this issue too, only with Python 3.11 on Windows GitHub Actions workflow: https://github.com/Kosmorro/lib/actions/runs/4795432929/jobs/8529978278

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry/issues/7611#issuecomment-1501539967

**Comment by Deuchnord** [comment]
Not sure to understand what I have to do: I have put the script you gave in a file and tried to run it (with and without `poetry run`), and locally I have this:

```
I am not in the poetry environment and this is not the right answer
Traceback (most recent call last):
  File "/Users/jerome/.../venv.py", line 6, in <module>
    import virtualenv
ModuleNotFoundError: No module named 'virtualenv'
```

I don't understand what I'm doing wrong here

**Comment by Deuchnord** [comment]
Fixed on my CI, the issue cames from my `pyproject.toml` that still had the old `tool.poetry.dev-dependencies` section. After moving to the new `tool.poetry.group.dev.dependencies` style, the CI passed again.

**Comment by MycroftKang** [comment]
I have confirmed that this bug occurs in `virtualenv` version 20.16.5. (poetry 1.4.2)

**Comment by zxia-wish** [comment]
Can confirm the problem with virtualenv 20.23.0 (latest at this time)

**Comment by byt3bl33d3r** [comment]
Seems to happen when installing the `neo4j` library as well. Python `3.11.3` , Poetry `1.5.1` & `virtualenv` 20.23.0:

```
vscode ➜ /workspaces/wat(main) $ poetry add neo4j
Using version ^5.9.0 for neo4j

Updating dependencies
Resolving dependencies... (0.2s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing neo4j (5.9.0): Failed

  ChefBuildError

  Backend 'setuptools.build_meta' is not available.

  at /usr/local/py-utils/venvs/poetry/lib/python3.11/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with neo4j (5.9.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "neo4j (==5.9.0)"'.
```

**Comment by assuiedmilan** [comment]
Still present in the current version. Hope this is a priority, downgrading my poetry version

**Comment by Xunil32** [comment]
> For those experiencing this issue: **update your lock files**. It might've been luck (intermittent failure and all...), but here it started to behave again.[1] That would explain the inability to reproduce this bug as well.
> 
> [1] ...and then immediately stumble into #7572, as I'm using Hypercorn, but that one is better understood and can be worked around without downgrading.

Solved for me as well. Poetry 1.5.1 on WIndows 10

**Comment by amdokamal** [comment]
Hope this helps someone out there. Stumbled upon a similar issue with Gitlab-CI runner (image: python:3.10.12-alpine3.18) even though everything was smooth working on Windows/Linux desktop setups. I followed the described "Interim Solutions", but alas... After digging I realized some dependencies were trying to build in the background, but were missing the essential tools for building. Once I added "apk add g++ musl-dev python3-dev" to the image, and everything was back to running as it should.

**Comment by lucinvitae** [comment]
I can confirm that my team hit this issue when attempting to upgrade to poetry 1.5.1; downgrading back to poetry 1.3.2 fixes the issue.

**Comment by gaby** [comment]
I'm running into the same error when using the `windows-latest` runner for Github Actions. The CI works fine for py3.10 and py3.11, but fails for py3.8, 3.9 with the same error:

```
ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.

  at C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\poetry\installation\chef.py:147 in _prepare
      143| 
      144|                 error = ChefBuildError("\n\n".join(message_parts))
      145| 
      146|             if error is not None:
    > 147|                 raise error from None
      148| 
      149|             return path
      150| 
      151|     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with olefile (0.46) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "olefile (==0.46)"'.


  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.

  at C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\poetry\installation\chef.py:147 in _prepare
      143| 
      144|                 error = ChefBuildError("\n\n".join(message_parts))
      145| 
      146|             if error is not None:
    > 147|                 raise error from None
      148| 
      149|             return path
      150| 
      151|     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with compressed-rtf (1.0.6) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "compressed-rtf (==1.0.6)"'.
```

**Comment by nurbscoder** [comment]
I have the same issue on a CI system using windows. On the system, I install poetry on the fly using pip (`python -m pip install poetry`). This was working fine for a long time. Suddenly, it stopped working and I got the same issue during `poetry install`, without changing anything (just restarting the CI job).

Investigating the difference took me to the point, that the failing job was using a newer version of virtualenv (20.24.0). By changing the poetry installation to `python -m pip install poetry virtualenv==20.23.1 it worked again.

So, it seams that the latest version of `virtualenv` is not compatible with poetry.

**Comment by xaviernogueira** [comment]
I have encountered the same issue with poetry==1.5.1, python 3.11, but only on "windows-latest" in my GitHub actions. Works fine on "ubuntu-latest". 

I downgraded to poetry==1.3.2 which works now, but would love to be able to deploy on the latest versions. Devs please address!

**Comment by nozwock** [comment]
@xaviernogueira I'm having the exact issue on a 'windows-latest' action. Switching to `poetry` 1.3.2 worked for me. Updating lock file did nothing.

**Comment by MrTeferi** [comment]
We had this same issue with packages `htmlmin` and `csscompressor` in the CI for [Photoshop-Python-API](https://github.com/loonghao/photoshop-python-api/actions/runs/5878249952/job/15939932237#step:4:311) . Running `poetry upgrade` and writing a new lock fixed one of them but not the other, then a different packaged popped the same issue. Updating pip, setuptools, and wheel beforehand again did not fix the issue. Finally the issue was fixed using the above recommendation of using an older `virtualenv`:
`python -m pip install poetry virtualenv==20.23.1`

Thanks a bunch! Hope this issue can be resolved for real in the future.

**Comment by ddoan** [comment]
We hit this with poetry 1.6.1 installing pandas 2.0.3.

![20230824_21h02m27s_grim](https://github.com/python-poetry/poetry/assets/993727/326a4029-1bce-43fa-80cd-6957fef079bd)

<img width="734" alt="Screenshot 2023-08-24 at 7 43 11 PM" src="https://github.com/python-poetry/poetry/assets/993727/9afac22b-cff5-4f33-be85-5d11ce8ddb31">

**Comment by pdobacz** [comment]
Same issue running in github-actions with: windows-latest, poetry 1.6.1, virtualenv 20.24.4, python 3.10.11. Happens during installation of pybloom-live (4.0.0) or fire (0.5.0). Interestingly, it never failed for fire before pybloom-live was added, as if only the number of deps mattered.

Downgrading to 1.3.2 or repeating the `poetry install` command both work as workarounds.

**Comment by KyleKing** [comment]
I was having this issue in my GitHub Actions Windows CI Pipeline. Without downgrading, I could workaround this issue by ensuring `setuptools` was installed in poetry's environment, but YMMV.

For a `pipx` install of `poetry`, this worked for me:

```sh
pipx install poetry==1.6.1
pipx inject poetry setuptools==68.1.2
```

And this should be a more general fix:

```sh
poetry self add setuptools
```

**Comment by rez0n** [comment]
Same issue.
```
Note: This error originates from the build backend, and is likely not a problem with poetry but with mysqlclient (2.2.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "mysqlclient (==2.2.0)"'.
```
Solved by downgrading to 1.3.2

**Comment by iamjpotts** [comment]
I just ran into this on an Azure DevOps pipeline run from the `ubuntu-latest` vmPool. It did not happen in the Docker containers that were being built based on `python:3.9-slim` images, and did not happen on the same pipeline an hour earlier.

Worked around it by downgrading to `poetry<1.4`

**Comment by kaqmak** [comment]
We are getting the same issue on our Azure DevOps pipeline with `poetry=1.6.1` on image `python:3.11-slim-bullseye`. Repeatedly rerunning the failed pipeline eventually "solves" the problem.

**Comment by euri10** [comment]
I tried every other option presented here, all failed.

What striked me is that I have several stages in my gitlab CI, all with the very same poetry install, all were working and just one failed at some point recently.

The only difference is the image used : so I switched from `  image: python` that was the only stage failing in my CI to `  image: python:3.11` and it is suddently working again.

**Comment by robbotorigami** [comment]
I spent a couple hours looking into this, and I think I've identified the root cause (or at least *a* root cause) for this issue. I've set up a [test repo](https://github.com/robbotorigami/poetry-bug-7611), that fairly reliably replicates this in the github actions runner. 

I believe the root cause is when multiple `setup.py` based dependencies are being installed from a source distribution for the first time on a system (in my example, `future` and `restructuredtext-lint`). Poetry will build both of these dependencies into a wheel in parallel. For each dependency it identifies using that they depend on setuptools, checks if setuptools is in the artifact cache, finds that it isn't, and then attempts to download a distribution for setuptools. Since there are two threads running in parallel trying to download the same file, there is a race condition where one thread succeeds and one fails (I believe this is predominately an issue for windows, with how it handles concurrent access to the file system). For the one that fails, the exception is caught, and pased up the call trace as a status return code until it is silently ignored here: [installer.run()](https://github.com/python-poetry/poetry/blob/719831a759e7e37e010b65ff7dad926977e27fd1/src/poetry/installation/chef.py#L80). Then, poetry proceeds to attempt to build the distribution, which fails because setuptools was never installed in the virtual environment for that dependency. I modify the executor in my github actions run so that it prints out the stack trace when exceptions are encountered, which can be seen here: [Test #14](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811). The relevant section:
```bash
Traceback (most recent call last):
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 767, in _download_link
    original_archive = self._download_archive(operation, link)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 857, in _download_archive
    with atomic_open(archive) as f:
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\requests\utils.py", line 307, in atomic_open
    os.replace(tmp_name, filename)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\8d\\aa\\9e\\5ebe452d7977c93fb8e0db884b6b167954ac9814e1f25125b4552d76c8\\tmpui9rw792' -> 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\8d\\aa\\9e\\5ebe452d7977c93fb8e0db884b6b167954ac9814e1f25125b4552d76c8\\setuptools-68.2.2-py3-none-any.whl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 286, in _execute_operation
    result = self._do_execute_operation(operation)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 387, in _do_execute_operation
    result: int = getattr(self, f"_execute_{method}")(operation)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 512, in _execute_install
    status_code = self._install(operation)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 550, in _install
    archive = self._download(operation)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 754, in _download
    return self._download_link(operation, link)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 773, in _download_link
    cached_file.unlink(missing_ok=True)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\pathlib.py", line 1[20](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:21)6, in unlink
    self._accessor.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\8d\\aa\\9e\\5ebe452d7977c93fb8e0db884b6b167954ac9814e1f25125b4552d76c8\\setuptools-68.2.2-py3-none-any.whl'

Traceback (most recent call last):
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 767, in _download_link
    original_archive = self._download_archive(operation, link)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 857, in _download_archive
    with atomic_open(archive) as f:
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\requests\utils.py", line 307, in atomic_open
    os.replace(tmp_name, filename)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\be\\01\\ba\\eabeb6a7ad74ee2a0542e0479545034db7365479427d5[26](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:27)7875[27](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:28)6c906\\tmpn385zi8y' -> 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\be\\01\\ba\\eabeb6a7ad74ee2a0542e0479545034db7365479427d5267875276c906\\wheel-0.41.2-py3-none-any.whl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line [28](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:29)6, in _execute_operation
    result = self._do_execute_operation(operation)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 387, in _do_execute_operation
    result: int = getattr(self, f"_execute_{method}")(operation)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 512, in _execute_install
    status_code = self._install(operation)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 550, in _install
    archive = self._download(operation)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 754, in _download
    return self._download_link(operation, link)
  File "C:\Users\runneradmin\.local\venv\lib\site-packages\poetry\installation\executor.py", line 773, in _download_link
    cached_file.unlink(missing_ok=True)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\pathlib.py", line 1206, in unlink
    self._accessor.unlink(self)
PermissionError: [WinError [32](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:33)] The process cannot access the file because it is being used by another process: 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\be\\01\\ba\\eabeb6a7ad74ee2a0542e04795450[34](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:35)db7[36](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:37)5479427d5267875276c906\\wheel-0.[41](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:42).2-py3-none-any.whl'


  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.

  at ~\.local\venv\lib\site-packages\poetry\installation\chef.py:147 in _prepare
      1[43](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:44)| 
      1[44](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:45)|                 error = ChefBuildError("\n\n".join(message_parts))
      1[45](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:46)| 
      1[46](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:47)|             if error is not None:
    > 1[47](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:48)|                 raise error from None
      1[48](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:49)| 
      1[49](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:50)|             return path
      1[50](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:51)| 
      1[51](https://github.com/robbotorigami/poetry-bug-7611/actions/runs/6412718462/job/17410500811#step:6:52)|     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with future (0.18.3) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "future (==0.18.3)"'.
```
Which shows the errors resulting from concurrent access to the artifact cache

Note that when replicating this issue setuptools needs to not be present already in the artifact cache (which is presumably why this is mostly affecting CI, and why pre installing setuptools fixes it in some cases). `poetry cache clear --all .` doesn't seem to remove it, so I've been manually removing the folder when I've been testing this.

I'm not exactly sure how this problem should be solved. The right solution probably involves some sort of locking mechanism for the artifact cache being implemented to prevent concurrent downloads of the same distribution package. The return value of `installer.run` should probably be checked in some manner to aid in future debugging. It could also be used in a retry loop, though that seems like a much hackier solution than locking.

Another workaround that should address the issue is:
```bash
poetry config installer.max-workers 1
```
since this will prevent two builds from happening in parallel (this will likely be much slower than running `poetry install` repeatedly though, so might not actually be of value).

**Comment by radoering** [comment]
Great finding. Sounds very plausible. 👍 

> The right solution probably involves some sort of locking mechanism for the artifact cache being implemented to prevent concurrent downloads of the same distribution package.

Agreed.

> The return value of installer.run should probably be checked in some manner to aid in future debugging.

We have already added better logging in master (see #8479), but still had no idea why the installation of build dependencies fails.

**Comment by iamjpotts** [comment]
I started seeing the failures in `python:3.9` based images also. On the Azure CI VM, setup tools was already installed, so that wasn't a viable workaround.

@robbotorigami this works so far:

```
poetry config installer.max-workers 1
```

**Comment by radoering** [comment]
Thanks to @robbotorigami (https://github.com/python-poetry/poetry/issues/7611#issuecomment-1747836233) I was able to reproduce the issue and provide a fix in #8517. Feel free to try the PR.

**Comment by inducer** [comment]
Sorry to (possibly?) be the bearer of bad news here: [This build](https://github.com/inducer/relate/actions/runs/6763710692/job/18381158386?pr=1038) appears to fail (on Windows) with a very similar symptom to what is described here, despite using poetry 1.7.0, which contains #8517. :thinking: 

```
  � Installing django-codemirror-widget (0.5.0)

  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.
  
  Traceback (most recent call last):
    File "C:\Users\runneradmin\.local\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\importlib\__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 994, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "C:\Users\RUNNER~1\AppData\Local\Temp\tmp5cl80_pe\.venv\Lib\site-packages\setuptools\__init__.py", line 8, in <module>
      import distutils.core
  ModuleNotFoundError: No module named 'distutils'
  

  at ~\.local\venv\Lib\site-packages\poetry\installation\chef.py:166 in _prepare
      162| 
      163|                 error = ChefBuildError("\n\n".join(message_parts))
      164| 
      165|             if error is not None:
    > 166|                 raise error from None
      167| 
      168|             return path
      169| 
      170|     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with django-codemirror-widget (0.5.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "django-codemirror-widget (==0.5.0)"'.
````

Notably, the suggested command succeeds:
```
pip wheel --no-cache-dir --use-pep517 "django-codemirror-widget (==0.5.0)"                                                                                               andreas@arc 15:25
/home/andreas/src/env-3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py:111: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pip._vendor.pkg_resources import find_distributions
Collecting django-codemirror-widget==0.5.0
  Downloading django-codemirror-widget-0.5.0.tar.gz (6.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: django-codemirror-widget
  Building wheel for django-codemirror-widget (pyproject.toml) ... done
  Created wheel for django-codemirror-widget: filename=django_codemirror_widget-0.5.0-py3-none-any.whl size=7918 sha256=994b804c1d4228457b59ce78a09d2be116f56aeba47a5c968504343582afb26c
  Stored in directory: /tmp/pip-ephem-wheel-cache-1cu5q9ol/wheels/35/bd/a5/48fb66e57f3161108f210d9dbcb36732bf7afcd6e63a4f38da
/home/andreas/src/env-3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_dists.py:73: DeprecationWarning: Unimplemented abstract methods {'locate_file'}
  return cls(files, info_location)
Successfully built django-codemirror-widget
```

**Comment by scottshambaugh** [comment]
I continuing to see the same build failure on Windows, Ubuntu, and MacOSX despite using poetry 1.7.0 which contained the supposed fix, see this workflow: https://github.com/scottshambaugh/monaco/actions/runs/6763933260/job/18381632398

**Comment by timwie** [comment]
It's a different error, the key difference being `ModuleNotFoundError: No module named 'distutils'`. That's because distutils is removed in Python 3.12. @scottshambaugh this is fixed in [numpy 1.26](https://numpy.org/doc/stable/release/1.26.0-notes.html).

**Comment by scottshambaugh** [comment]
Thank you @timwie! That did indeed resolve my error.

**Comment by dimbleby** [comment]
that is not even close to being the same error: and by reproducing it with pip you have anyway proved that it is not a poetry problem.

**Comment by PedroH183** [comment]
Same issue here, the Interim Solutions works for me.
