### ISSUE TITLE
 'HTTPResponse' object has no attribute 'strict'

### ISSUE THREAD

**Issue by aakashrshah** [python-poetry/poetry#7936]
- **Poetry version**: Poetry (version 1.4.2)
- **Python version**: Python:  3.10.10
- **OS version and name**: macOS 13.2
- **pyproject.toml**: https://gist.github.com/aakashrshah/16d755f1bfacdcee1bb2cd2a66a409f0

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
```

  AttributeError

  'HTTPResponse' object has no attribute 'strict'

  at ~/Library/Caches/pypoetry/virtualenvs/rubber-duck-py3.10/lib/python3.10/site-packages/cachecontrol/serialize.py:54 in dumps
       50│                 ),
       51│                 u"status": response.status,
       52│                 u"version": response.version,
       53│                 u"reason": text_type(response.reason),
    →  54│                 u"strict": response.strict,
       55│                 u"decode_content": response.decode_content,
       56│             }
       57│         }
       58│ 
```

I am not able to install or add packages and blocked significantly. I do not see this issue on internet. Am i using a wrong python version? this is the latest version of poetry , shall i revert?

**Comment by dimbleby** [comment]
this is https://github.com/ionrock/cachecontrol/issues/292

however since poetry requirements do not allow urllib 2.0, this shows that you, or whatever you used to install poetry, have upgraded something that you should not have done

please close

**Comment by dimbleby** [comment]
PS I do not know why you write here "I do not see this issue on internet." when, as I now see, you have already commented on that other issue

**Comment by Secrus** [comment]
Poetry has `urllib3` pinned below 2.0, so you had to mess something up on your end (for example by installing your project and poetry into the same environment). In any case, this is not Poetry's fault.

**Comment by aakashrshah** [comment]
Good by me if we want to close it. Currently I removed the line with strict in cache control. 

I tried it on python 3.10, 3.11 with latest poetry and latest pip.

I don’t know what did I mess up on my end. 

Thanks though.

**Comment by aakashrshah** [comment]
> Can be the case that you are still using poetry < 1.2; in that case you will need to pin urllib to < 2 because it was a dev dependency as you can see [here](https://github.com/python-poetry/poetry/blob/1.1.15/pyproject.toml#L81).

I surely confirm I am using latest version 1.4.2 in and out(global) of my virtual environment.

**Comment by chanwutk** [comment]
@aakashrshah I am having the same issue (this issue started to happen a couple days ago).
Would you mind if I ask you how did you "removed the line with strict in cache control", please?

**Comment by FachengG** [comment]
@chanwutk 
use `None `to replace `response.strict`.
Not sure about side-effect, but it will work again.

**Comment by aakashrshah** [comment]
> @aakashrshah I am having the same issue (this issue started to happen a couple days ago).
> Would you mind if I ask you how did you "removed the line with strict in cache control", please?

Hi @chanwutk 

I deleted line 54
python3.10/site-packages/cachecontrol/serialize.py:54

**Comment by chanwutk** [comment]
Thank you!!

**Comment by lucafulgenzi** [comment]
System config:
- Python: 3.11.3
- Poetry: 1.4.2

Working with `urllib3==1.26.9` installed globally

**Comment by trigremm** [comment]
poetry add "urllib3<=2.0" solved the topic issue for my projects

**Comment by Yanqiao4396** [comment]
> `poetry add "urllib3<=2.0"` solved the topic issue for my projects

Didn't work on mine, unfortunately

**Comment by trigremm** [comment]
> > `poetry add "urllib3<=2.0"` solved the topic issue for my projects
> 
> 
> 
> Didn't work on mine, unfortunately

Have you tried to check urllib3 version and if in case of >=2.0 downgrade it via pip and repeat ?

**Comment by trigremm** [comment]
> > > `poetry add "urllib3<=2.0"` solved the topic issue for my projects
> > 
> > 
> > Didn't work on mine, unfortunately
> 
> Have you tried to check urllib3 version and if in case of >=2.0 downgrade it via pip and repeat ?

urllib3 Remove strict parameter #2064
https://github.com/urllib3/urllib3/pull/2064

**Comment by vetsin** [comment]
Had this issue seemingly because i've installed my package into the same pyenv environment poetry exists on -- 

had to manually add the del line in `~/.pyenv/versions/3.11.3/lib/python3.11/site-packages/cachecontrol/serialize.py`'s `prepare_response` method as follows:

```
        del cached["response"]["strict"]
        return HTTPResponse(body=body, preload_content=False, **cached["response"])
```

From there I was able to `poetry update`

**Comment by paultiplady** [comment]
Maybe context-specific, but I fixed this by using `pyenv` to split poetry into a separate venv.

`pyenv local myproject 3.7.9` sets pyenv to look for executables first in `myproject` (the local project-specific venv) followed by `3.7.9` (the global python version where I've installed poetry). You could also create a completely separate venv just for poetry.

Another approach might be to use [pipx](https://pypa.github.io/pipx/) to run poetry, since it handles isolating the executable in its own venv.

**Comment by vcidst** [comment]
Downgrading requests worked for me, `pip install requests==2.28`

Is this error related to https://github.com/ionrock/cachecontrol/pull/301 which was merged yesterday?
I was using poetry==1.1.13 and the docker builds started failing since poetry installs the latest version of requests package.

**Comment by amites** [comment]
add this reference which provides some guidance for how to migrate from 1.x to 2.x for urllib3
https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html

if you pin versions for

```
urllib3==1.26.16
requests==2.29.0
```

everything continues to work

**Comment by nick-maykr** [comment]
> 

Turns out, not all responses come with "strict" key. I had to add the following in `prepare_response` in `site-packages/cachecontrol/serialize.py`:

        if cached["response"].get("strict") is not None:
          del cached["response"]["strict"]

**Comment by diegoquintanav** [comment]
In my case, I started getting this error after something I did with pipx. Running `pipx install poetry --force` fixed poetry for me.

**Comment by XChikuX** [comment]
Just always pin these dependencies for poetry and you should be good.
```
[tool.poetry.dependencies]
python = "^3.10"
charset-normalizer = "^3.1.0"  # Needed cause of a bug in poetry
urllib3 = "^1.26.16"  # Needed cause of a bug in poetry
```
Just downgrade urllib3 with pip in case you broke poetry.

**Comment by jeromegit** [comment]
Running this worked for me: 
`pip install -U requests==2.28.2 urllib3==1.26.15`
(using poetry 1.4)

**Comment by tew9** [comment]
I had the same issue, and I fix it by deleting the terminal I was running it from and rerun it in another terminal.
It was a virtual environment issue for me.
Issue: I was debugging using a terminal which is running poetry virtual environment.
Fix: I deleted the terminal and create the new one that was on base environment and everything works fine.

hope that helps

**Comment by sir-kokabi** [comment]
I've deleted all poetry virtual environments and created a new virtual environment again, and the problem was resolved.
windows 11.

**Comment by bramses** [comment]
For me, I had moved my folder with `poetry` into a subfolder later on and for some reason that broke everything.

1. poetry shell was in `~/folder_a`
2. i moved `folder_a` into `~/new_parent_folder/folder_a`
3. this broke `poetry add`, `poetry install` etc

still not sure why

**Comment by hungiito** [comment]
I had the same problem when installing `poetry` in a virtual environment. I found that when running poetry install in a virtual environment, poetry still use outdated `urllib3` and `requests` installed in the machine. So I tried to upgrade urllib3 and requests (outside of virtual environment) and it works.

In short
```bash
deactivate # deactivate virtual env (if activated)
pip3 install --upgrade pip
pip3 install --upgrade urllib3 requests
```

**Comment by Telofy** [comment]
I was about to fork Poetry and create a PR that adds the `urllib3 = "^1.26.16"` dependency to Poetry's pyproject.toml, but something tells me there's probably some recondite reason for the omission of the dependency? Or has just no one gotten around to adding it?

**Comment by Secrus** [comment]
> I was about to fork Poetry and create a PR that adds the `urllib3 = "^1.26.16"` dependency to Poetry's pyproject.toml, but something tells me there's probably some recondite reason for the omission of the dependency? Or has just no one gotten around to adding it?

Yes, there reason is that this bug is not present in Poetry anymore. This is only a case for non-standard installation which are discouraged.

**Comment by Telofy** [comment]
Oh, thx! There must've been something nonstandard about my environment because I used mamba/conda for another project. But now I'm running into #8679 instead of this one. ^.^

**Comment by LaoshuBaby** [comment]
To above all, why not check `pip install poetry urllib3 requests --upgrade`? I meet with this issue today when I run "poetry install", I can't downgrade urllib3 because other part of project lock the dependency version, and only upgrade those 2 like hungiito wrote won't work.

That's because I forgot to upgrade the most important poetry-1.4.1, and that version require urllib3<2.0.0,>=1.26.0

But now the latest version of poetry is 1.8.1, and everythings work fluently, don't need to manually edit any link in site-packages. Now what about try to upgrade those 3 package all?

♥

**Comment by hungiito** [comment]
@LaoshuBaby Did you try upgrading `urllib3` and `requests` outside of poetry's virtual environment?

**Comment by LaoshuBaby** [comment]
> @LaoshuBaby Have you tried upgrading `urllib3` and `requests` outside of Poetry's virtual environment? In my case, I installed Poetry in a `venv` folder and noticed that Poetry uses the `urllib3` in root environment rather than in `venv` directory

I did not specify a venv environment

**Comment by hungiito** [comment]
> > @LaoshuBaby Have you tried upgrading `urllib3` and `requests` outside of Poetry's virtual environment? In my case, I installed Poetry in a `venv` folder and noticed that Poetry uses the `urllib3` in root environment rather than in `venv` directory
> 
> I did not specify a venv environment

Can you try upgrading both pip and poetry

```python
pip install --upgrade pip poetry
```

**Comment by LaoshuBaby** [comment]
@hungiito 

> To above all, why not check `pip install poetry urllib3 requests --upgrade`?
> -- In my reply https://github.com/python-poetry/poetry/issues/7936#issuecomment-1973528255

I execute this command and upgrade everything to the latest, which can solve the problem originally raised by this issue.

> Can you try upgrading both pip and poetry

You can do it without upgrading pip, but it will not cause problems if you upgrade it according to my test.

(In short, now my pip, requests, urllib3, and poetry are all up to date.)

That's why I recommend you upgrade(if you can) them.

**Comment by ChrCoello** [comment]
As @jeromegit wrote earlier, this is surely due to using Poetry 1.4. 
Same error arose when we had to use conda (Azure ML Compute) as virtual environment manager (always try to avoid conda at any cost...). Then when one installs poetry on a freshly created conda environment using conda
```console
conda install poetry
```,  Poetry 1.4 is installed, by the same time downgrading `urlib3` and `requests`.
Using pip to install Poetry solved the "issue", installing latest Poetry 1.8 without any downgrade
```console
pip install poetry
```
